### ISSUE TITLE
compaction: excessive reallocation during input list formatting

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14071]
As @raphaelsc said in https://github.com/scylladb/scylladb/pull/13907:

with off-strategy, input list size can be close to 1k, which will lead to unneeded reallocations when formatting the list for logging.

in the past, we faced stalls in this area, and excessive reallocation (log2 ~1k = ~10) may have contributed to that.

**Comment by bhalevy** [comment]
Fixed in https://github.com/scylladb/scylladb/pull/13907 by https://github.com/scylladb/scylladb/commit/5544d12f18e9109cdaab5cf384bf477c6ae0a4d9

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint please consider backport to all active OSS versions + 2022.1

**Comment by avikivity** [comment]
Backported to 5.2, 5.1. 5.3 already had the fix.

**Comment by DoronArazii** [comment]
@avikivity did you forgot to remove the labels? or it's in purpose?

**Comment by avikivity** [comment]
Forgot.

**Comment by pdbossman** [comment]
I don't quite understand the mapping from OSS to enterprise yet and it's not explicitly mentioned - what release of 2022.2.x is this coming in?

**Comment by bhalevy** [comment]
> I don't quite understand the mapping from OSS to enterprise yet and it's not explicitly mentioned - what release of 2022.2.x is this coming in?

According to https://github.com/scylladb/scylla-enterprise/commits/branch-2022.2
it's going to be 2022.2.12
