### ISSUE TITLE
test_create_100tables: OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14806]
Seen in debug mode https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/245/testReport/
```
AssertionError: test_data/c-s-profiles/create_100tables.cql:1823:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
  test_data/c-s-profiles/create_100tables.cql:1840:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
  test_data/c-s-profiles/create_100tables.cql:1840:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.
  test_data/c-s-profiles/create_100tables.cql:1847:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
  test_data/c-s-profiles/create_100tables.cql:1866:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
  test_data/c-s-profiles/create_100tables.cql:1875:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
  test_data/c-s-profiles/create_100tables.cql:1875:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.
  test_data/c-s-profiles/create_100tables.cql:1882:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
  test_data/c-s-profiles/create_100tables.cql:1891:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
  test_data/c-s-profiles/create_100tables.cql:1910:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
  test_data/c-s-profiles/create_100tables.cql:1974:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
  
assert not "test_data/c-s-profiles/create_100tables.cql:1823:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Clien...on defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042\n"
```

There are no errors printed in the logs.

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/245/artifact/logs-full.debug.038/dtest-gw2.log
```
08:24:52,498 794     cql_additional_tests           DEBUG    cql_additional_tests.py:7075 | test_create_100tables: Create 100+ tables by simple_test_100tables.cql
08:30:07,786 794     ccm                            DEBUG    cluster.py          :709  | test_create_100tables: node1: (EE) test_data/c-s-profiles/create_100tables.cql:1823:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
08:30:07,786 794     ccm                            DEBUG    cluster.py          :709  | test_create_100tables: node1: (EE) test_data/c-s-profiles/create_100tables.cql:1840:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
08:30:07,786 794     ccm                            DEBUG    cluster.py          :709  | test_create_100tables: node1: (EE) test_data/c-s-profiles/create_100tables.cql:1840:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.
08:30:07,786 794     ccm                            DEBUG    cluster.py          :709  | test_create_100tables: node1: (EE) test_data/c-s-profiles/create_100tables.cql:1847:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
08:30:07,786 794     ccm                            DEBUG    cluster.py          :709  | test_create_100tables: node1: (EE) test_data/c-s-profiles/create_100tables.cql:1866:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
08:30:07,786 794     ccm                            DEBUG    cluster.py          :709  | test_create_100tables: node1: (EE) test_data/c-s-profiles/create_100tables.cql:1875:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
08:30:07,786 794     ccm                            DEBUG    cluster.py          :709  | test_create_100tables: node1: (EE) test_data/c-s-profiles/create_100tables.cql:1875:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.
08:30:07,787 794     ccm                            DEBUG    cluster.py          :709  | test_create_100tables: node1: (EE) test_data/c-s-profiles/create_100tables.cql:1882:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
08:30:07,787 794     ccm                            DEBUG    cluster.py          :709  | test_create_100tables: node1: (EE) test_data/c-s-profiles/create_100tables.cql:1891:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
08:30:07,787 794     ccm                            DEBUG    cluster.py          :709  | test_create_100tables: node1: (EE) test_data/c-s-profiles/create_100tables.cql:1910:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
08:30:07,787 794     ccm                            DEBUG    cluster.py          :709  | test_create_100tables: node1: (EE) test_data/c-s-profiles/create_100tables.cql:1974:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
08:30:07,787 794     ccm                            DEBUG    cluster.py          :709  | test_create_100tables: node1: 
08:30:08,075 794     errors                         ERROR    conftest.py         :207  | test_create_100tables: test failed: 
self = <cql_additional_tests.TestsCQLAdditional object at 0x7f3f012224d0>

    def test_create_100tables(self):
        """
        The scenario referenced https://github.com/scylladb/scylla/issues/2923
    
        Create 100 tables, and try to restart the scylla-server of two nodes
        """
        jvm_args = [
            '--twcs-max-window-count', '100',
        ]
        self.cluster.populate(3).start(jvm_args=jvm_args)
        nodes = self.cluster.nodelist()
        schema_file = "test_data/c-s-profiles/create_100tables.cql"
        assert os.path.exists(schema_file), "schema file doesn't exist"
    
        logger.debug("Create 100+ tables by simple_test_100tables.cql")
    
        out, err = nodes[0].run_cqlsh(cmds="SOURCE '%s'" % schema_file, show_output=True, return_output=True)
>       assert not err, err
E       AssertionError: test_data/c-s-profiles/create_100tables.cql:1823:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1840:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1840:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.
E         test_data/c-s-profiles/create_100tables.cql:1847:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1866:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1875:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1875:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.
E         test_data/c-s-profiles/create_100tables.cql:1882:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1891:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1910:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1974:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         
E       assert not "test_data/c-s-profiles/create_100tables.cql:1823:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Clien...on defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042\n"

cql_additional_tests.py:7078: AssertionError
08:30:08,075 794     errors                         ERROR    conftest.py         :207  | test_create_100tables: test failed: 
self = <cql_additional_tests.TestsCQLAdditional object at 0x7f3f012224d0>

    def test_create_100tables(self):
        """
        The scenario referenced https://github.com/scylladb/scylla/issues/2923
    
        Create 100 tables, and try to restart the scylla-server of two nodes
        """
        jvm_args = [
            '--twcs-max-window-count', '100',
        ]
        self.cluster.populate(3).start(jvm_args=jvm_args)
        nodes = self.cluster.nodelist()
        schema_file = "test_data/c-s-profiles/create_100tables.cql"
        assert os.path.exists(schema_file), "schema file doesn't exist"
    
        logger.debug("Create 100+ tables by simple_test_100tables.cql")
    
        out, err = nodes[0].run_cqlsh(cmds="SOURCE '%s'" % schema_file, show_output=True, return_output=True)
>       assert not err, err
E       AssertionError: test_data/c-s-profiles/create_100tables.cql:1823:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1840:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1840:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.
E         test_data/c-s-profiles/create_100tables.cql:1847:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1866:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1875:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1875:Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.
E         test_data/c-s-profiles/create_100tables.cql:1882:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1891:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1910:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         test_data/c-s-profiles/create_100tables.cql:1974:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042
E         
E       assert not "test_data/c-s-profiles/create_100tables.cql:1823:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Clien...on defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.84.1:9042\n"

cql_additional_tests.py:7078: AssertionError
08:30:14,135 794     dtest_setup                    DEBUG    dtest_setup.py      :637  | test_create_100tables: removing ccm cluster test at: /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.dtest/dtest-ea2ds7y1
08:30:14,210 794     dtest_setup                    DEBUG    dtest_setup.py      :641  | test_create_100tables: clearing ssl stores from [/jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.dtest/dtest-ea2ds7y1] directory
08:30:14,210 794     dtest_setup                    DEBUG    dtest_setup.py      :83   | test_create_100tables: Freeing cluster ID 84: link /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.dtest/84
```

**Comment by bhalevy** [comment]
@tgrabiec can you please look into this?

**Comment by DoronArazii** [comment]
> @tgrabiec can you please look into this?

@tgrabiec ping

**Comment by nyh** [comment]
Issue #15306 seems to be the same "Connection defunct by heartbeat" problem when creating a lot of materialized views (which, internally, requires creating more tables). There are 10 more issues reporting the same error when doing schema operations while the machine is busy - https://github.com/scylladb/scylladb/issues?q=is%3Aissue+is%3Aopen+%22connection+defunct+by+heartbeat%22 .

**Comment by kostja** [comment]
Should be addressed by Kamil's work on generating schema version in group0

**Comment by mykaul** [comment]
> Should be addressed by Kamil's work on generating schema version in group0

@kbr-scylla - that's a 6.0 material now, no?

**Comment by kbr-scylla** [comment]
> @kbr-scylla - that's a 6.0 material now, no?

Group 0 schema versioning yes, but I see absolutely no evidence that it would fix the root cause of this failure (which should be understood before we propose that there's any connection.)

So I don't think we should move the milestone here, whatever is the cause here is probably a bug still present in 5.4 and thus should be independently fixed and then backported, without relation to the group 0 schema versioning patch.

**Comment by mykaul** [comment]
> > @kbr-scylla - that's a 6.0 material now, no?
> 
> Group 0 schema versioning yes, but I see absolutely no evidence that it would fix the root cause of this failure (which should be understood before we propose that there's any connection.)
> 
> So I don't think we should move the milestone here, whatever is the cause here is probably a bug still present in 5.4 and thus should be independently fixed and then backported, without relation to the group 0 schema versioning patch.

@kbr-scylla - any updates? It's still on 5.4 milestone, but I'm not sure what is addressing this issue.

**Comment by bhalevy** [comment]
The test still fails in debug mode with `'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.1.1:9042`
But I see no `Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.` anymore.

See https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/266/artifact/logs-full.debug.022/dtest-gw0.log
```
08:04:05,706 790     conftest                       INFO     conftest.py         :255  | test_create_100tables: Starting execution of test_create_100tables at 2023-11-19 08:04:05.706967
08:04:05,707 790     dtest_setup                    INFO     dtest_setup.py      :794  | test_create_100tables: cluster ccm directory: /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs
08:04:05,707 790     ccm                            DEBUG    cluster.py          :754  | test_create_100tables: ScyllaCluster: cassandra_version=7b08886e8dd8a62a97c5a7467bd77190440eb5af docker_image=None install_dir=None scylla_mode=None default_wait_other_notice_timeout=120 default_wait_for_binary_proto=420
08:04:05,708 790     ccm                            DEBUG    cluster.py          :754  | test_create_100tables: ScyllaCluster: load_from_repository: install_dir=/jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/7b08886e8dd8a62a97c5a7467bd77190440eb5af scylla_mode=debug default_wait_other_notice_timeout=600 default_wait_for_binary_proto=900
08:04:05,710 790     ccm                            DEBUG    cluster.py          :754  | test_create_100tables: Started cluster 'test' version 5.5.0-dev installed in /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/7b08886e8dd8a62a97c5a7467bd77190440eb5af
08:04:05,711 790     dtest_setup                    DEBUG    dtest_setup.py      :694  | test_create_100tables: Scylla mode is 'debug'
08:04:05,711 790     dtest_setup                    DEBUG    dtest_setup.py      :695  | test_create_100tables: Cluster *_request_timeout_in_ms=30000, range_request_timeout_in_ms=90000, cql request_timeout=90
08:04:05,717 790     dtest_setup                    DEBUG    dtest_setup.py      :762  | test_create_100tables: Done setting configuration options:
{   'cas_contention_timeout_in_ms': 30000,
    'consistent_cluster_management': False,
    'counter_write_request_timeout_in_ms': 60000,
    'initial_token': None,
    'num_tokens': 256,
    'phi_convict_threshold': 5,
    'range_request_timeout_in_ms': 90000,
    'read_request_timeout_in_ms': 30000,
    'request_timeout_in_ms': 30000,
    'ring_delay_ms': 10000,
    'skip_wait_for_gossip_to_settle': 0,
    'task_ttl_in_seconds': 0,
    'truncate_request_timeout_in_ms': 90000,
    'write_request_timeout_in_ms': 30000}
08:04:05,722 790     dtest_setup                    DEBUG    dtest_setup.py      :61   | test_create_100tables: Allocated cluster ID 1: /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs
08:04:05,877 790     ccm                            DEBUG    cluster.py          :754  | test_create_100tables: start_nodes: no_wait=False wait_for_binary_proto=True wait_other_notice=True force_wait_for_cluster_start=True
08:04:05,881 790     ccm                            DEBUG    cluster.py          :754  | test_create_100tables: node1: Starting scylla: args=['/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/conf/scylla.yaml', '--log-to-stdout', '1', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--twcs-max-window-count', '100', '--api-address', '127.0.1.1', '--collectd-hostname', 'ip-10-0-3-169.ec2.internal.node1', '--smp', '2', '--memory', '1024M', '--developer-mode', 'true', '--default-log-level', 'info', '--blocked-reactor-notify-ms', '5000', '--collectd', '0', '--overprovisioned', '--prometheus-address', '127.0.1.1', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--max-networking-io-control-blocks', '1000'] wait_other_notice=True wait_for_binary_proto=True
08:04:11,727 790     ccm                            DEBUG    cluster.py          :754  | test_create_100tables: node1: Starting scylla-jmx: args=['/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/bin/symlinks/scylla-jmx', '-Dapiaddress=127.0.1.1', '-Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder', '-Djava.rmi.server.hostname=127.0.1.1', '-Dcom.sun.management.jmxremote', '-Dcom.sun.management.jmxremote.host=127.0.1.1', '-Dcom.sun.management.jmxremote.port=7199', '-Dcom.sun.management.jmxremote.rmi.port=7199', '-Dcom.sun.management.jmxremote.local.only=false', '-Xmx256m', '-XX:+UseSerialGC', '-Dcom.sun.management.jmxremote.authenticate=false', '-Dcom.sun.management.jmxremote.ssl=false', '-jar', '/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/bin/scylla-jmx-1.0.jar']
08:04:12,186 790     ccm                            DEBUG    cluster.py          :754  | test_create_100tables: node2: Starting scylla: args=['/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node2/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node2/conf/scylla.yaml', '--log-to-stdout', '1', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--twcs-max-window-count', '100', '--api-address', '127.0.1.2', '--collectd-hostname', 'ip-10-0-3-169.ec2.internal.node2', '--smp', '2', '--memory', '1024M', '--developer-mode', 'true', '--default-log-level', 'info', '--blocked-reactor-notify-ms', '5000', '--collectd', '0', '--overprovisioned', '--prometheus-address', '127.0.1.2', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--max-networking-io-control-blocks', '1000'] wait_other_notice=True wait_for_binary_proto=True
08:05:46,644 790     ccm                            DEBUG    cluster.py          :754  | test_create_100tables: node2: Starting scylla-jmx: args=['/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node2/bin/symlinks/scylla-jmx', '-Dapiaddress=127.0.1.2', '-Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder', '-Djava.rmi.server.hostname=127.0.1.2', '-Dcom.sun.management.jmxremote', '-Dcom.sun.management.jmxremote.host=127.0.1.2', '-Dcom.sun.management.jmxremote.port=7199', '-Dcom.sun.management.jmxremote.rmi.port=7199', '-Dcom.sun.management.jmxremote.local.only=false', '-Xmx256m', '-XX:+UseSerialGC', '-Dcom.sun.management.jmxremote.authenticate=false', '-Dcom.sun.management.jmxremote.ssl=false', '-jar', '/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node2/bin/scylla-jmx-1.0.jar']
08:05:47,104 790     ccm                            DEBUG    cluster.py          :754  | test_create_100tables: node3: Starting scylla: args=['/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node3/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node3/conf/scylla.yaml', '--log-to-stdout', '1', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--twcs-max-window-count', '100', '--api-address', '127.0.1.3', '--collectd-hostname', 'ip-10-0-3-169.ec2.internal.node3', '--smp', '2', '--memory', '1024M', '--developer-mode', 'true', '--default-log-level', 'info', '--blocked-reactor-notify-ms', '5000', '--collectd', '0', '--overprovisioned', '--prometheus-address', '127.0.1.3', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--max-networking-io-control-blocks', '1000'] wait_other_notice=True wait_for_binary_proto=True
08:08:04,345 790     ccm                            DEBUG    cluster.py          :754  | test_create_100tables: node3: Starting scylla-jmx: args=['/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node3/bin/symlinks/scylla-jmx', '-Dapiaddress=127.0.1.3', '-Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder', '-Djava.rmi.server.hostname=127.0.1.3', '-Dcom.sun.management.jmxremote', '-Dcom.sun.management.jmxremote.host=127.0.1.3', '-Dcom.sun.management.jmxremote.port=7199', '-Dcom.sun.management.jmxremote.rmi.port=7199', '-Dcom.sun.management.jmxremote.local.only=false', '-Xmx256m', '-XX:+UseSerialGC', '-Dcom.sun.management.jmxremote.authenticate=false', '-Dcom.sun.management.jmxremote.ssl=false', '-jar', '/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node3/bin/scylla-jmx-1.0.jar']
08:08:04,974 790     cql_additional_tests           DEBUG    cql_additional_tests.py:7084 | test_create_100tables: Create 100+ tables by simple_test_100tables.cql
08:11:46,273 790     ccm                            DEBUG    cluster.py          :754  | test_create_100tables: node1: (EE) test_data/c-s-profiles/create_100tables.cql:1997:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.1.1:9042
08:11:46,273 790     ccm                            DEBUG    cluster.py          :754  | test_create_100tables: node1: 
Warnings :
SimpleStrategy replication class is not recommended, but was used for keyspace veraminetest. You may suppress this warning by delisting SimpleStrategy from replication_strategy_warn_list configuration option, or make it into an error by listing this replication strategy on replication_strategy_fail_list.

Using Replication Factor replication_factor=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.


08:11:46,577 790     errors                         ERROR    conftest.py         :226  | test_create_100tables: test failed: 
self = <cql_additional_tests.TestsCQLAdditional object at 0x7fcdca41ff90>

    @unmark.next_gating  # https://github.com/scylladb/scylladb/issues/14806
    def test_create_100tables(self):
        """
        The scenario referenced https://github.com/scylladb/scylla/issues/2923
    
        Create 100 tables, and try to restart the scylla-server of two nodes
        """
        jvm_args = [
            '--twcs-max-window-count', '100',
        ]
        self.cluster.populate(3).start(jvm_args=jvm_args)
        nodes = self.cluster.nodelist()
        schema_file = "test_data/c-s-profiles/create_100tables.cql"
        assert os.path.exists(schema_file), "schema file doesn't exist"
    
        logger.debug("Create 100+ tables by simple_test_100tables.cql")
    
        out, err = nodes[0].run_cqlsh(cmds="SOURCE '%s'" % schema_file, show_output=True, return_output=True)
>       assert not err, err
E       AssertionError: test_data/c-s-profiles/create_100tables.cql:1997:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.1.1:9042
E         
E       assert not "test_data/c-s-profiles/create_100tables.cql:1997:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.1.1:9042\n"

cql_additional_tests.py:7087: AssertionError
08:11:46,577 790     errors                         ERROR    conftest.py         :226  | test_create_100tables: test failed: 
self = <cql_additional_tests.TestsCQLAdditional object at 0x7fcdca41ff90>

    @unmark.next_gating  # https://github.com/scylladb/scylladb/issues/14806
    def test_create_100tables(self):
        """
        The scenario referenced https://github.com/scylladb/scylla/issues/2923
    
        Create 100 tables, and try to restart the scylla-server of two nodes
        """
        jvm_args = [
            '--twcs-max-window-count', '100',
        ]
        self.cluster.populate(3).start(jvm_args=jvm_args)
        nodes = self.cluster.nodelist()
        schema_file = "test_data/c-s-profiles/create_100tables.cql"
        assert os.path.exists(schema_file), "schema file doesn't exist"
    
        logger.debug("Create 100+ tables by simple_test_100tables.cql")
    
        out, err = nodes[0].run_cqlsh(cmds="SOURCE '%s'" % schema_file, show_output=True, return_output=True)
>       assert not err, err
E       AssertionError: test_data/c-s-profiles/create_100tables.cql:1997:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.1.1:9042
E         
E       assert not "test_data/c-s-profiles/create_100tables.cql:1997:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.1.1:9042\n"

cql_additional_tests.py:7087: AssertionError
```

**Comment by bhalevy** [comment]
The node logs look good and all table creations seem to be done in a timely manner.
For example, https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/266/artifact/logs-full.debug.022/1700381511594_cql_additional_tests.py%3A%3ATestsCQLAdditional%3A%3Atest_create_100tables/node1.log
```
INFO  2023-11-19 08:08:06,113 [shard 0:stmt] migration_manager - Create new Keyspace: KSMetaData{name=veraminetest, strategyClass=org.apache.cassandra.locator.SimpleStrategy, strategyOptions={replication_factor=1}, cfMetaData={}, durable_writes=1, userTypes=org.apache.cassandra.config.UTMetaData@0x6110013fb868}
INFO  2023-11-19 08:08:06,122 [shard 0:stmt] schema_tables - Creating keyspace veraminetest
INFO  2023-11-19 08:08:06,662 [shard 0:stmt] schema_tables - Schema version changed to a9d52c8b-32c7-38bb-9944-bf6bd7f3124d
WARN  2023-11-19 08:08:06,662 [shard 0:stmt] create_keyspace - SimpleStrategy replication class is not recommended, but was used for keyspace veraminetest. You may suppress this warning by delisting SimpleStrategy from replication_strategy_warn_list configuration option, or make it into an error by listing this replication strategy on replication_strategy_fail_list.
WARN  2023-11-19 08:08:06,662 [shard 0:stmt] create_keyspace - Using Replication Factor replication_factor=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.
...
INFO  2023-11-19 08:11:25,556 [shard 0:stmt] schema_tables - Schema version changed to 712347e1-e630-3f83-bbda-4f94c88aa010
INFO  2023-11-19 08:11:30,261 [shard 0: gms] migration_manager - Requesting schema pull from 127.0.1.2:0
INFO  2023-11-19 08:11:30,261 [shard 0: gms] migration_manager - Pulling schema from 127.0.1.2:0
WARN  2023-11-19 08:11:33,835 [shard 0:stmt] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
INFO  2023-11-19 08:11:34,607 [shard 0:stmt] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x6190000f7d80[cfId=41311df0-86b3-11ee-9de4-bdcf9f102eae,ksName=veraminetest,cfName=yarabinarysearchresults,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(6d617463686573:org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type))),comment=,readRepairChance=0,dcLocalReadRepairChance=0,tombstoneGcOptions={"mode":"timeout","propagation_delay_in_seconds":"3600"},gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.UUIDType,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=customerguid, type=org.apache.cassandra.db.marshal.UUIDType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=actionid, type=org.apache.cassandra.db.marshal.LongType, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=base64expression, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=compiledexpression, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=filescancount, type=org.apache.cassandra.db.marshal.LongType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=matches, type=org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type), kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=41311df1-86b3-11ee-9de4-bdcf9f102eae,droppedColumns={},collections={6d617463686573 : org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)},indices={}]
INFO  2023-11-19 08:11:35,670 [shard 0:comp] compaction - [Compact system_schema.dropped_columns 41d0e060-86b3-11ee-9de4-bdcf9f102eae] Compacting [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/me-3gb7_0mok_5cwg02efupd2orsq7i-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/me-3gb7_0mrb_16fs02efupd2orsq7i-big-Data.db:level=0:origin=memtable]
INFO  2023-11-19 08:11:36,327 [shard 0:comp] compaction - [Compact system_schema.dropped_columns 41d0e060-86b3-11ee-9de4-bdcf9f102eae] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f/me-3gb7_0mrb_4tm002efupd2orsq7i-big-Data.db:level=0]. 20kB to 11kB (~57% of original) in 592ms = 35kB/s. ~256 total partitions merged to 7.
INFO  2023-11-19 08:11:36,342 [shard 0:comp] compaction - [Compact system_schema.tables 4238a2e0-86b3-11ee-9de4-bdcf9f102eae] Compacting [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3gb7_0mrb_5hehc2efupd2orsq7i-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3gb7_0mqg_4rw9s2efupd2orsq7i-big-Data.db:level=0:origin=compaction]
INFO  2023-11-19 08:11:37,339 [shard 0:comp] compaction - [Compact system_schema.tables 4238a2e0-86b3-11ee-9de4-bdcf9f102eae] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3gb7_0mrc_285sw2efupd2orsq7i-big-Data.db:level=0]. 57kB to 32kB (~55% of original) in 899ms = 64kB/s. ~256 total partitions merged to 7.
INFO  2023-11-19 08:11:37,365 [shard 0:comp] compaction - [Compact system_schema.computed_columns 42d30e20-86b3-11ee-9de4-bdcf9f102eae] Compacting [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/computed_columns-cc7c7069374033c192a4c3de78dbd2c4/me-3gb7_0mol_2u8k02efupd2orsq7i-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/computed_columns-cc7c7069374033c192a4c3de78dbd2c4/me-3gb7_0mrc_1pii82efupd2orsq7i-big-Data.db:level=0:origin=memtable]
INFO  2023-11-19 08:11:38,255 [shard 0:comp] compaction - [Compact system_schema.computed_columns 42d30e20-86b3-11ee-9de4-bdcf9f102eae] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/computed_columns-cc7c7069374033c192a4c3de78dbd2c4/me-3gb7_0mrd_2t5z42efupd2orsq7i-big-Data.db:level=0]. 20kB to 11kB (~56% of original) in 786ms = 26kB/s. ~256 total partitions merged to 7.
INFO  2023-11-19 08:11:38,283 [shard 0:comp] compaction - [Compact system_schema.scylla_tables 435efa70-86b3-11ee-9de4-bdcf9f102eae] Compacting [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/me-3gb7_0mod_00ffk2efupd2orsq7i-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/me-3gb7_0mrc_3ybgg2efupd2orsq7i-big-Data.db:level=0:origin=memtable]
INFO  2023-11-19 08:11:39,062 [shard 0:comp] compaction - [Compact system_schema.scylla_tables 435efa70-86b3-11ee-9de4-bdcf9f102eae] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/me-3gb7_0mre_23nrk2efupd2orsq7i-big-Data.db:level=0]. 22kB to 13kB (~59% of original) in 677ms = 33kB/s. ~256 total partitions merged to 7.
INFO  2023-11-19 08:11:39,098 [shard 0:comp] compaction - [Compact system_schema.columns 43da44f0-86b3-11ee-9de4-bdcf9f102eae] Compacting [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/me-3gb7_0mrb_2pqio2efupd2orsq7i-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/me-3gb7_0mqf_1lvc02efupd2orsq7i-big-Data.db:level=0:origin=compaction]
INFO  2023-11-19 08:11:39,687 [shard 0: gms] schema_tables - Schema version changed to 712347e1-e630-3f83-bbda-4f94c88aa010
INFO  2023-11-19 08:11:39,688 [shard 0: gms] migration_manager - Schema merge with 127.0.1.2:0 completed
INFO  2023-11-19 08:11:39,733 [shard 0:stmt] schema_tables - Creating veraminetest.yarabinarysearchresults id=41311df0-86b3-11ee-9de4-bdcf9f102eae version=c61797a0-adcc-3b6f-b897-034cfb184bcd
WARN  2023-11-19 08:11:40,293 [shard 0:stmt] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
INFO  2023-11-19 08:11:40,545 [shard 0:stmt] schema_tables - Schema version changed to d3cb1d65-613b-31b0-b415-bb84fc98d7b9
INFO  2023-11-19 08:11:41,484 [shard 0:comp] compaction - [Compact system_schema.columns 43da44f0-86b3-11ee-9de4-bdcf9f102eae] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3d9zk4bs/test/node1/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/me-3gb7_0mrf_10ng02efupd2orsq7i-big-Data.db:level=0]. 132kB to 73kB (~55% of original) in 2371ms = 55kB/s. ~256 total partitions merged to 7.
INFO  2023-11-19 08:11:46,578 [shard 0:main] init - Signal received; shutting down
```

**Comment by mykaul** [comment]
> Should be addressed by Kamil's work on generating schema version in group0

@kostja - is this a 5.4 item, or shall we defer it to 6.0?

**Comment by kostja** [comment]
The original patch addressing this was reverted due to a regression discovered only at a post-merge dtest run (ugh), and Kamil has very little time to push this further. While he's making progress and this is super important to many of our testing scenarios, I believe we missed the 5.4 window, so, 6.0.

**Comment by kbr-scylla** [comment]
@kostja but why do you think that group 0 schema versioning would address this?

**Comment by kostja** [comment]
@kbr-scylla I am going from addressing the possible known causes to digging into the unknown, that's it.

**Comment by mykaul** [comment]
@kostja - what's the latest here?

**Comment by kbr-scylla** [comment]
Group 0 schema versioning was merged. @kostja believes that it might fix this issue -- so let's see if it keeps reproducing.

**Comment by kostja** [comment]
The new schema versioning patch was merged. 100 tablets should now get created in a matter of minutes. There is still a performance regression as you add more tables - which will not be addressed now. But I think we can and should re-enable the 100 tables test.

**Comment by mykaul** [comment]
@kostja - I know we did the work - but have we enabled the test?

**Comment by kostja** [comment]
No, it still takes a significant amount of time.

**Comment by kbr-scylla** [comment]
> No, it still takes a significant amount of time

But did the failure actually reproduce?

**Comment by kbr-scylla** [comment]
2024.1.4 run with logs attached: https://github.com/scylladb/scylla-enterprise/issues/4153

**Comment by kbr-scylla** [comment]
Similar failure here when trying to create a materialized view: https://github.com/scylladb/scylladb/issues/16818
also ends with "Connection defunct by heartbeat': 'Client request timeout"

there are some clues from @sylwiaszunejko  https://github.com/scylladb/scylladb/issues/16818#issuecomment-2063663342

it could potentially be a driver issue

**Comment by kbr-scylla** [comment]
Due to similarity of https://github.com/scylladb/scylladb/issues/16818, and since https://github.com/scylladb/scylladb/issues/16818 contains more analysis, marking this as `blocked` -- let's focus on https://github.com/scylladb/scylladb/issues/16818 first, if we manage to fix it, we'll retest this one as well.

**Comment by emdroid** [comment]
Since the https://github.com/scylladb/scylladb/issues/16818 doesn't reproduce any more and it has been closed, plus the group0 tombstone GC has been improved, I think we can close this one as well.

**Comment by Annamikhlin** [comment]
seen again on https://jenkins.scylladb.com/job/scylla-master/job/dtest-release-with-raft/749/testReport/junit/cql_additional_tests/TestsCQLAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_create_100tables/

```
self = <cql_additional_tests.TestsCQLAdditional object at 0x7f78b24ca6c0>

    @unmark.next_gating  # https://github.com/scylladb/scylladb/issues/14806
    @pytest.mark.skip_if(with_feature("tablets") & issue_open("#18180"))
    def test_create_100tables(self):
        """
        The scenario referenced https://github.com/scylladb/scylla/issues/2923
    
        Create 100 tables, and try to restart the scylla-server of two nodes
        """
        jvm_args = [
            "--twcs-max-window-count",
            "100",
        ]
        self.cluster.populate(3).start(jvm_args=jvm_args)
        nodes = self.cluster.nodelist()
        schema_file = "test_data/c-s-profiles/create_100tables.cql"
        assert os.path.exists(schema_file), "schema file doesn't exist"
    
        logger.debug("Create 100+ tables by simple_test_100tables.cql")
    
        out, err = nodes[0].run_cqlsh(cmds="SOURCE '%s'" % schema_file, show_output=True, return_output=True)
>       assert not err, err
E       AssertionError: test_data/c-s-profiles/create_100tables.cql:1974:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.37.1:9042
E         
E       assert not "test_data/c-s-profiles/create_100tables.cql:1974:OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.37.1:9042\n"

cql_additional_tests.py:7074: AssertionError
```

Logs: 
[dtest-gw9.log](https://github.com/user-attachments/files/21773454/dtest-gw9.log)

[1755132580621_cql_additional_tests.py__TestsCQLAdditional__test_create_100tables.zip](https://github.com/user-attachments/files/21773455/1755132580621_cql_additional_tests.py__TestsCQLAdditional__test_create_100tables.zip)

**Comment by emdroid** [comment]
@AbhinavKumarJha could you please have a look at this one?

**Comment by Annamikhlin** [comment]
seen again on https://jenkins.scylladb.com/job/scylla-master/job/dtest-release-with-raft/778/testReport/cql_additional_tests/TestsCQLAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_create_100tables/


Logs:
[dtest-gw7.log](https://github.com/user-attachments/files/22319053/dtest-gw7.log)
[1757804802730_cql_additional_tests.py__TestsCQLAdditional__test_create_100tables.zip](https://github.com/user-attachments/files/22319055/1757804802730_cql_additional_tests.py__TestsCQLAdditional__test_create_100tables.zip)

**Comment by emdroid** [comment]
In the last failure, it seems that all the tables have been actually created, and there is no error in the nodes. The first table is "binary_global" and the last one in the SQL file is "yarabinarysearchresults":

```
INFO  2025-09-13 23:04:25,085 [shard 0: gms] schema_tables - Creating veraminetest.binary_global id=fdf8be90-90f5-11f0-a59a-8a4aea0d98d9 version=fdf8be91-90f5-11f0-a59a-8a4aea0d98d9
INFO  2025-09-13 23:04:25,089 [shard 0: gms] migration_manager - Gossiping my schema version fdf8ddbc-90f5-11f0-afeb-db4344026d79
INFO  2025-09-13 23:04:25,089 [shard 0: gms] schema_tables - Schema version changed to fdf8ddbc-90f5-11f0-afeb-db4344026d79
INFO  2025-09-13 23:04:25,090 [shard 0: gms] view_building_coordinator - No base table to process.

...

INFO  2025-09-13 23:06:27,594 [shard 0: gms] schema_tables - Creating veraminetest.yarabinarysearchresults id=46f4faa0-90f6-11f0-a59a-8a4aea0d98d9 version=46f4faa1-90f6-11f0-a59a-8a4aea0d98d9
INFO  2025-09-13 23:06:37,700 [shard 0:main] compaction_manager - Asked to stop
INFO  2025-09-13 23:06:37,701 [shard 0:main] view_update_generator - Terminating background fiber
```

it looks similar (with the very similar timestamps) for all the nodes.

What I noticed is that the difference between these is approx. 2 min (23:04:25 - 23:06:27), so it could be that there is a 120s timeout somewhere. Plus the last table is missing the schema version change logs after creating the table (although there is approx. 10s gap after the last table creation log).

**Comment by emdroid** [comment]
In the previous failure ([jenkins.scylladb.com/job/scylla-master/job/dtest-release-with-raft/749/testReport/junit/cql_additional_tests/TestsCQLAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_create_100tables](https://jenkins.scylladb.com/job/scylla-master/job/dtest-release-with-raft/749/testReport/junit/cql_additional_tests/TestsCQLAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_create_100tables/)) even the schema version change logs are there (and no gap), but again the time between first and last table creation is just slightly above the 2 min.

**Comment by emdroid** [comment]
The default timeout of `node.run_cqlsh()` is apparently 600s ... but there can be some other timeout of 2 min somewhere, causing this "Connection defunct by heartbeat" - the message is also mentioning `Session.execute[_async](timeout)` - @AbhinavKumarJha can you try to find this and what the timeout is?

**Comment by AbhinavKumarJha** [comment]
I think these recent re-occurences are unrelated to this issue. The core crux here was schema version mismatch
`schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.`

In the recent re-occurences, I cant find anything related to schema mismatch.

As folks have predicted in this thread above, the `Group 0 schema versioning` might have actually solved this issue.

Lets close this and open another issue.

**Comment by mykaul** [comment]
@AbhinavKumarJha - please open a new issue then.

**Comment by AbhinavKumarJha** [comment]
created https://github.com/scylladb/scylladb/issues/26236

**Comment by AbhinavKumarJha** [comment]
closing this now!!
