### ISSUE TITLE
[dtest] Tests / Sanity Tests-RAFT / replace_address_test.TestReplaceAddress.test_replace_node_same_ip[use_endpoint-rbo_disabled] is flakey

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#15713]
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6663/testReport/junit/replace_address_test/TestReplaceAddress/Tests___Sanity_Tests_RAFT___test_replace_node_same_ip_use_endpoint_rbo_disabled_/

```
failed on teardown with "AssertionError: Unexpected errors found: [('node1', ['ERROR 2023-10-15 08:56:50,518 [shard 0:stre] raft - [8a91912e-c2af-4007-be41-e07f41a44b75] Transferring snapshot to aa837d53-3491-4a20-b9eb-f8097c84ac00 failed with: raft::transport_error (Failed to execute virtual future<raft::snapshot_reply> service::raft_rpc::send_snapshot(raft::server_id, const raft::install_snapshot &, seastar::abort_source &) on leader aa837d53-3491-4a20-b9eb-f8097c84ac00: seastar::rpc::closed_error (connection is closed))'])]"
```

```
request = <SubRequest 'fixture_dtest_setup' for <Function test_replace_node_same_ip[use_endpoint-rbo_disabled]>>
dtest_config = <dtest_config.DTestConfig object at 0x7fbdb5dcb910>
fixture_dtest_setup_overrides = <dtest_setup_overrides.DTestSetupOverrides object at 0x7fbdb642bed0>
fixture_logging_setup = None, fixture_dtest_cluster_name = 'test'
fixture_dtest_create_cluster_func = <function DTestSetup.create_ccm_cluster at 0x7fbdb94de160>

    @pytest.fixture(scope='function', autouse=False)
    def fixture_dtest_setup(request,
                            dtest_config,
                            fixture_dtest_setup_overrides,
                            fixture_logging_setup,
                            fixture_dtest_cluster_name,
                            fixture_dtest_create_cluster_func):
    
        # do all of our setup operations to get the enviornment ready for the actual test
        # to run (e.g. bring up a cluster with the necessary config, populate variables, etc)
        initial_environment = copy.deepcopy(os.environ)
        dtest_setup = DTestSetup(dtest_config=dtest_config,
                                 setup_overrides=fixture_dtest_setup_overrides,
                                 cluster_name=fixture_dtest_cluster_name)
    
        cassandra_cluster = dtest_config.cassandra_version
    
        if not cassandra_cluster:
            if ((request.node.get_closest_marker('single_node') or
                    not request.node.get_closest_marker('no_boot_speedups'))
                    and not dtest_setup.dtest_config.tablets):  # workaround for https://github.com/scylladb/scylladb/issues/15152
                dtest_setup.cluster_options.setdefault('skip_wait_for_gossip_to_settle', 0)
    
            # Reduce waiting time for the nodes to hear from others before joining the ring.
            # Since all test cases run on localhost and there are no large test clusters
            # it's safe to reduce the value to save a lot of time while testing.
            # (Default value for the option is 30s)
            dtest_setup.cluster_options.setdefault('ring_delay_ms', 10000)
    
        cluster_options = request.node.get_closest_marker('cluster_options')
        if cluster_options:
            for name, value in cluster_options.kwargs.items():
                dtest_setup.cluster_options.setdefault(name, value)
    
        manager_install_dir = dtest_setup.prepare_scylla_manager() if request.node.get_closest_marker('scylla_manager') else None
        dtest_setup.initialize_cluster(fixture_dtest_create_cluster_func, manager_install_dir=manager_install_dir)
    
        # at this point we're done with our setup operations in this fixture
        # yield to allow the actual test to run
        yield dtest_setup
    
        # phew! we're back after executing the test, now we need to do
        # all of our teardown and cleanup operations
    
        reset_environment_vars(initial_environment)
        dtest_setup.jvm_args = []
    
        for con in dtest_setup.connections:
            con.cluster.shutdown()
        dtest_setup.connections = []
    
        rep_setup = getattr(request.node, "rep_setup", None)
        rep_call = getattr(request.node, "rep_call", None)
        failed = getattr(rep_setup, 'failed', False) or getattr(rep_call, 'failed', False)
    
        try:
            dtest_setup.cluster.stop(gently=True)
        except Exception as e:
            logger.error("Error stopping cluster: %s", str(e))
    
        try:
            if not dtest_setup.allow_log_errors:
                try:
>                   dtest_setup.check_errors_all_nodes()

conftest.py:346: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <dtest_setup.DTestSetup object at 0x7fbdb657bb10>
nodes = [<ccmlib.scylla_node.ScyllaNode object at 0x7fbdb4bdda10>, <ccmlib.scylla_node.ScyllaNode object at 0x7fbd8659bb90>, <...0>, <ccmlib.scylla_node.ScyllaNode object at 0x7fbd8659b410>, <ccmlib.scylla_node.ScyllaNode object at 0x7fbd865b4b90>]
exclude_errors = None, search_str = None, regex = False

    def check_errors_all_nodes(self, nodes=None, exclude_errors=None, search_str=None, regex=False):
        if nodes is None:
            nodes = self.cluster.nodelist()
    
        critical_errors = []
        found_errors = []
        for node in nodes:
            try:
                critical_errors_pattern = r'Assertion.*failed|AddressSanitizer'
                if self.ignore_cores_log_patterns:
                    expr = '|'.join(["({})".format(p) for p in set(self.ignore_cores_log_patterns)])
                    matches = node.grep_log(expr)
                    if matches:
                        logger.debug("Will ignore cores on {}. Found the following log messages: {}".format(
                            node.name, matches))
                        self.ignore_cores.append(node)
                if node not in self.ignore_cores:
                    critical_errors_pattern += "|Aborting"
                matches = node.grep_log(critical_errors_pattern)
                if matches:
                    critical_errors.append((node.name, [m[0].strip() for m in matches]))
            except FileNotFoundError:
                pass
            errors = self.check_errors(node=node, exclude_errors=exclude_errors, search_str=search_str, regex=regex,
                                       return_errors=True)
            if len(errors):
                found_errors.append((node.name, errors))
    
        if critical_errors:
            raise AssertionError('Critical errors found: {}\nOther errors: {}'.format(
                critical_errors, found_errors))
        if found_errors:
>           raise AssertionError('Unexpected errors found: {}'.format(found_errors))
E           AssertionError: Unexpected errors found: [('node1', ['ERROR 2023-10-15 08:56:50,518 [shard 0:stre] raft - [8a91912e-c2af-4007-be41-e07f41a44b75] Transferring snapshot to aa837d53-3491-4a20-b9eb-f8097c84ac00 failed with: raft::transport_error (Failed to execute virtual future<raft::snapshot_reply> service::raft_rpc::send_snapshot(raft::server_id, const raft::install_snapshot &, seastar::abort_source &) on leader aa837d53-3491-4a20-b9eb-f8097c84ac00: seastar::rpc::closed_error (connection is closed))'])]

dtest_setup.py:558: AssertionError
```

**Comment by mykaul** [comment]
@kbr-scylla - the error might be relevant to your team.

**Comment by kbr-scylla** [comment]
Ran on instance with fast NVMe disk. Plus it's not a timeout error, but `rpc::closed_error` during snapshot transfer.

**Comment by kbr-scylla** [comment]
[1697360249146_replace_address_test.py TestReplaceAddress test_replace_node_same_ip[use_endpoint-rbo_disabled].zip](https://github.com/scylladb/scylladb/files/12930395/1697360249146_replace_address_test.py.TestReplaceAddress.test_replace_node_same_ip.use_endpoint-rbo_disabled.zip)
[dtest-gw1.log](https://github.com/scylladb/scylladb/files/12930396/dtest-gw1.log)

dtest-gw1.log doesn't have anything interesting. End of test:
```
08:56:49,161 784     replace_address_test           INFO     replace_address_test.py:789  | test_replace_node_same_ip[use_endpoint-rbo_disabled]: Starting node 5 to replace node 5
08:56:49,199 784     ccm                            DEBUG    cluster.py          :709  | test_replace_node_same_ip[use_endpoint-rbo_disabled]: node5: Starting scylla: args=['/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kwiy0kqm/test/node5/bin/scylla', '--options-file', '/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kwiy0kqm/test/node5/conf/scylla.yaml', '--log-to-stdout', '1', '--abort-on-seastar-bad-alloc', '--abort-on-lsa-bad-alloc', '1', '--abort-on-internal-error', '1', '--auto-bootstrap', 'true', '--seed-provider-parameters', 'seeds=127.0.78.1', '--api-address', '127.0.78.5', '--collectd-hostname', 'ip-10-0-1-252.ec2.internal.node5', '--smp', '2', '--memory', '1024M', '--developer-mode', 'true', '--default-log-level', 'info', '--collectd', '0', '--overprovisioned', '--prometheus-address', '127.0.78.5', '--replace-address', '127.0.78.5', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--max-networking-io-control-blocks', '1000'] wait_other_notice=True wait_for_binary_proto=True
08:57:09,387 784     cassandra.cluster              WARNING  threading.py        :1038 | test_replace_node_same_ip[use_endpoint-rbo_disabled]: Host 127.0.78.5:9042 has been marked down
08:57:10,491 784     cassandra.pool                 WARNING  thread.py           :58   | test_replace_node_same_ip[use_endpoint-rbo_disabled]: Error attempting to reconnect to 127.0.78.5:9042, scheduling retry in 1.94 seconds: [Errno 111] Tried connecting to [('127.0.78.5', 9042)]. Last error: Connection refused
08:57:12,495 784     cassandra.pool                 WARNING  thread.py           :58   | test_replace_node_same_ip[use_endpoint-rbo_disabled]: Error attempting to reconnect to 127.0.78.5:9042, scheduling retry in 3.68 seconds: [Errno 111] Tried connecting to [('127.0.78.5', 9042)]. Last error: Connection refused
08:57:16,201 784     cassandra.pool                 WARNING  thread.py           :58   | test_replace_node_same_ip[use_endpoint-rbo_disabled]: Error attempting to reconnect to 127.0.78.5:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.78.5', 9042)]. Last error: Connection refused
08:57:18,280 784     ccm                            DEBUG    cluster.py          :709  | test_replace_node_same_ip[use_endpoint-rbo_disabled]: node5: Starting scylla-jmx: args=['/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kwiy0kqm/test/node5/bin/symlinks/scylla-jmx', '-Dapiaddress=127.0.78.5', '-Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder', '-Djava.rmi.server.hostname=127.0.78.5', '-Dcom.sun.management.jmxremote', '-Dcom.sun.management.jmxremote.host=127.0.78.5', '-Dcom.sun.management.jmxremote.port=7199', '-Dcom.sun.management.jmxremote.rmi.port=7199', '-Dcom.sun.management.jmxremote.local.only=false', '-Xmx256m', '-XX:+UseSerialGC', '-Dcom.sun.management.jmxremote.authenticate=false', '-Dcom.sun.management.jmxremote.ssl=false', '-jar', '/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kwiy0kqm/test/node5/bin/scylla-jmx-1.0.jar']
08:57:29,190 784     dtest_setup                    DEBUG    dtest_setup.py      :642  | test_replace_node_same_ip[use_endpoint-rbo_disabled]: removing ccm cluster test at: /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kwiy0kqm
08:57:29,358 784     dtest_setup                    DEBUG    dtest_setup.py      :646  | test_replace_node_same_ip[use_endpoint-rbo_disabled]: clearing ssl stores from [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kwiy0kqm] directory
08:57:29,358 784     dtest_setup                    DEBUG    dtest_setup.py      :85   | test_replace_node_same_ip[use_endpoint-rbo_disabled]: Freeing cluster ID 78: link /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/78
```

It seems that the test case itself succeeded. It was general sanity check at teardown -- checking that node logs contain no `ERROR`s.

Relevant node1 logs from that time:
```
INFO  2023-10-15 08:56:46,161 [shard 0:goss] gossip - Got shutdown message from 127.0.78.5, received_generation=1697360183, local_generation=1697360183
INFO  2023-10-15 08:56:46,161 [shard 0:goss] gossip - InetAddress 127.0.78.5 is now DOWN, status = shutdown
INFO  2023-10-15 08:56:49,009 [shard 0:main] raft_group_registry - marking Raft server 6c9e49dd-bf3a-4a07-b12f-dcfe3da73e6e as dead for raft groups
WARN  2023-10-15 08:56:50,431 [shard 0:main] raft_group_registry - Raft server id aa837d53-3491-4a20-b9eb-f8097c84ac00 cannot be translated to an IP address.
WARN  2023-10-15 08:56:50,515 [shard 0:goss] gossip - Fail to send EchoMessage to 127.0.78.5: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
ERROR 2023-10-15 08:56:50,518 [shard 0:stre] raft - [8a91912e-c2af-4007-be41-e07f41a44b75] Transferring snapshot to aa837d53-3491-4a20-b9eb-f8097c84ac00 failed with: raft::transport_error (Failed to execute virtual future<raft::snapshot_reply> service::raft_rpc::send_snapshot(raft::server_id, const raft::install_snapshot &, seastar::abort_source &) on leader aa837d53-3491-4a20-b9eb-f8097c84ac00: seastar::rpc::closed_error (connection is closed))
INFO  2023-10-15 08:56:50,532 [shard 0:comp] compaction - [Compact system.scylla_local c78d2240-6b38-11ee-9110-5f3ecacfb9d3] Compacting [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kwiy0kqm/test/node1/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3ga8_0ouq_343hs27f00vmi966z7-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kwiy0kqm/test/node1/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3ga8_0ou1_3ayep27f00vmi966z7-big-Data.db:level=0:origin=compaction]
INFO  2023-10-15 08:56:50,534 [shard 0:main] raft_group_registry - marking Raft server aa837d53-3491-4a20-b9eb-f8097c84ac00 as alive for raft groups
INFO  2023-10-15 08:56:50,543 [shard 0:comp] compaction - [Compact system.scylla_local c78d2240-6b38-11ee-9110-5f3ecacfb9d3] Compacted 2 sstables to [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kwiy0kqm/test/node1/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3ga8_0ouq_360xt27f00vmi966z7-big-Data.db:level=0]. 12kB to 6kB (~52% of original) in 7ms = 1MB/s. ~256 total partitions merged to 4.
INFO  2023-10-15 08:56:51,548 [shard 0:comp] compaction - [Compact system.scylla_local c82829c0-6b38-11ee-9110-5f3ecacfb9d3] Compacting [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kwiy0kqm/test/node1/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3ga8_0our_38dtc27f00vmi966z7-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kwiy0kqm/test/node1/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3ga8_0ouq_360xt27f00vmi966z7-big-Data.db:level=0:origin=compaction]
WARN  2023-10-15 08:56:51,549 [shard 0:goss] gossip - Fail to send EchoMessage to 127.0.78.5: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
INFO  2023-10-15 08:56:51,557 [shard 0:comp] compaction - [Compact system.scylla_local c82829c0-6b38-11ee-9110-5f3ecacfb9d3] Compacted 2 sstables to [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-kwiy0kqm/test/node1/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3ga8_0our_39ge927f00vmi966z7-big-Data.db:level=0]. 12kB to 6kB (~52% of original) in 7ms = 1MB/s. ~256 total partitions merged to 4.
WARN  2023-10-15 08:56:52,880 [shard 0:goss] gossip - Fail to send EchoMessage to 127.0.78.5: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
WARN  2023-10-15 08:56:53,514 [shard 0:goss] gossip - Fail to send EchoMessage to 127.0.78.5: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
WARN  2023-10-15 08:56:54,880 [shard 0:goss] gossip - Fail to send EchoMessage to 127.0.78.5: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
WARN  2023-10-15 08:56:55,880 [shard 0:goss] gossip - Fail to send EchoMessage to 127.0.78.5: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
WARN  2023-10-15 08:56:56,542 [shard 0:goss] gossip - Fail to send EchoMessage to 127.0.78.5: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
WARN  2023-10-15 08:56:57,881 [shard 0:goss] gossip - Fail to send EchoMessage to 127.0.78.5: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
WARN  2023-10-15 08:56:58,515 [shard 0:goss] gossip - Fail to send EchoMessage to 127.0.78.5: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
WARN  2023-10-15 08:56:59,881 [shard 0:goss] gossip - Fail to send EchoMessage to 127.0.78.5: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
INFO  2023-10-15 08:57:00,715 [shard 0:stre] storage_service - replace[08b22006-9fe1-4131-a6d7-f0d54f044fa5]: Added replacing_node=127.0.78.5 to replace existing_node=127.0.78.5, coordinator=127.0.78.5
INFO  2023-10-15 08:57:00,715 [shard 0:stre] token_metadata - Added node 127.0.78.5 as pending replacing endpoint which replaces existing node 127.0.78.5
INFO  2023-10-15 08:57:00,881 [shard 0:goss] gossip - InetAddress 127.0.78.5 is now UP, status = UNKNOWN
```


from a glance, it looks like the problem was transient and the cluster recovered eventually and finished the test.

**Comment by avikivity** [comment]
Yes, but we need to do something.

1. decide the error is expected and swallow it in core
2. decide the error is expected and ignore it in the test
3. decide the error is unexpected (despite that the cluster recovered) and fix something

**Comment by kostja** [comment]
@kbr-scylla there is a big overlap of this test with a similar test in test.py; please consider merging the two.

**Comment by kbr-scylla** [comment]
What might have happened, is that the leader has an old RPC client object to the old incarnation of node5 (from before replace).
As soon as it learns that the new replacing host maps to the same IP, it tries to send a snapshot to it.
However, the messaging layer reuses the old RPC client, which was established to the old node.
So it tries to send a snapshot on the old connection, which is now closed, and we're unlucky in that this is the first message that observes that the connection is closed, so it gets that error.

The leader retries sending snapshot, so eventually it establishes a new connection to the new node, and the entire procedure succeeds.

**Comment by kbr-scylla** [comment]
Nodes are dropping all connections to nodes about which they learn of being DOWN, but this is racing with the test. If the test replacing quickly enough, the leader might have not dropped the connections yet and could try reusing some of them e.g. for snapshot transfer RPC.

The most elegant way would be to solve this on the messaging layer, by associating the RPC clients with host IDs, which is part of the larger project of moving the code-base to be host-ID based and pushing IP mappings down to the messaging layer. I think @bhalevy was working on adding host IDs to `msg_addr`s which would be enough here. (Is that project still ongoing?)

The lazy solution is to ignore the error in the test for the time being.

**Comment by bhalevy** [comment]
> think @bhalevy was working on adding host IDs to `msg_addr`s which would be enough here.

@tgrabiec had reservations about this approach as having both host_id and ip address in msg_address could be ambiguous.  The direction he wanted to go id to convert msg_address to use only host_id and map it to an inet_address for messaging purposes as close as possible to the wire, so we won't have to carry the ip address around until we need it.

**Comment by bhalevy** [comment]
> The lazy solution is to ignore the error in the test for the time being.

That should be fine if the error is benign

**Comment by tchaikov** [comment]
@kostja @kbr-scylla hello gents, since this test failure is surfacing frequently, i am going to add a workaround to silence this failure on the dtest end if no objections. as discussed above, this is far from a real fix. so i am not assigning this issue to myself.

**Comment by kbr-scylla** [comment]
@tchaikov yes please, thank you. You can simply ignore the test by using `ignore_log_patterns`  with e.g. `"Transferring snapshot"` in the dtest.

**Comment by kbr-scylla** [comment]
Note: this issue is most likely not occuring anymore (a workaround was added to dtest, please confirm @tchaikov). Still I'd keep it open until the root cause is addressed (https://github.com/scylladb/scylladb/issues/15713#issuecomment-1777350751)

**Comment by tchaikov** [comment]
> Note: this issue is most likely not occuring anymore (a workaround was added to dtest, please confirm @tchaikov). Still I'd keep it open until the root cause is addressed ([#15713 (comment)](https://github.com/scylladb/scylladb/issues/15713#issuecomment-1777350751))

sorry, i missed this ping. yes, i confirm.

**Comment by juliayakovlev** [comment]
It looks like this issue was happened in SCT test.

@kbr-scylla @tchaikov 
please check if it is the same issue with this scenario (described below)? If yes - should we add same workaround (ignore this failure)

Nemesis `BootstrapStreamingError`
```
< t:2024-07-07 10:59:24,884 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-07-07 10:59:24.883: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=40ea38a5-9626-4f06-93bd-f91b27627e1e: nemesis_name=BootstrapStreamingError target_node=Node longevity-parallel-topology-schema--db-node-e3e9d046-22 [34.229.162.175 | 10.12.9.246]
```

New node `longevity-parallel-topology-schema--db-node-e3e9d046-23` was added and started bootstrap
```
< t:2024-07-07 11:00:39,351 f:common.py       l:66   c:sdcm.utils.raft.common p:DEBUG > Starting bootstrap process longevity-parallel-topology-schema--db-node-e3e9d046-23
< t:2024-07-07 11:00:39,351 f:common.py       l:76   c:sdcm.utils.raft.common p:DEBUG > Stop bootstrap process after log message: 'setup_group0: successfully joined group 0'

2024-07-07T11:05:19.485+00:00 longevity-parallel-topology-schema--db-node-e3e9d046-23     !INFO | scylla[6608]:  [shard 0] raft_group0 - setup_group0: successfully joined group 0.
```

Interrupt bootstrap as planned by nemesis:
```
2024-07-07T11:05:20.312+00:00 longevity-parallel-topology-schema--db-node-e3e9d046-23   !NOTICE | sudo[6697]: scyllaadm : PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/systemctl stop scylla-server.service
```

Raft transport error on `longevity-parallel-topology-schema--db-node-e3e9d046-12`
```
Jul 07 11:05:20.313076 longevity-parallel-topology-schema--db-node-e3e9d046-12 scylla[11291]:  [shard 0] gossip - InetAddress 10.12.11.49 is now UP, status = UNKNOWN
Jul 07 11:05:20.367103 longevity-parallel-topology-schema--db-node-e3e9d046-12 scylla[11291]:  [shard 0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Jul 07 11:05:20.392967 longevity-parallel-topology-schema--db-node-e3e9d046-12 scylla[11291]:  [shard 0] raft_group_registry - marking Raft server 5f2e78c9-c1b2-47f3-87b4-048fd2589d0d as alive for raft groups
Jul 07 11:05:20.397481 longevity-parallel-topology-schema--db-node-e3e9d046-12 scylla[11291]:  [shard 0] schema_tables - Schema version changed to ae5857ee-6dd3-3b03-a464-60890c35d5e3
Jul 07 11:05:20.397555 longevity-parallel-topology-schema--db-node-e3e9d046-12 scylla[11291]:  [shard 0] migration_manager - Schema merge with 10.12.11.127:0 completed
Jul 07 11:05:20.565439 longevity-parallel-topology-schema--db-node-e3e9d046-12 scylla[11291]:  [shard 5] direct_failure_detector - unexpected exception when pinging 5f2e78c9-c1b2-47f3-87b4-048fd2589d0d: seastar::rpc::unknown_verb_error (unknown verb)
Jul 07 11:05:20.565667 longevity-parallel-topology-schema--db-node-e3e9d046-12 scylla[11291]:  [shard 0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Jul 07 11:05:20.583593 longevity-parallel-topology-schema--db-node-e3e9d046-12 scylla[11291]:  [shard 0] raft - [464d7c46-6c64-44fd-a232-56e1321f4673] Transferring snapshot to 5f2e78c9-c1b2-47f3-87b4-048fd2589d0d failed with: raft::transport_error (Failed to execute virtual future<raft::snapshot_reply> service::raft_rpc::send_snapshot(raft::server_id, const raft::install_snapshot &, seastar::abort_source &) on leader 5f2e78c9-c1b2-47f3-87b4-048fd2589d0d: seastar::rpc::closed_error (connection is closed))
```



## Packages

Scylla version: `2023.1.10-20240706.21cffccc1ccd` with build-id `87fcdaf894b5dfb25d26f12d7d4aed71b84bfd44`





Kernel Version: `5.15.0-1064-aws`


## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 5 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-parallel-topology-schema--db-node-e3e9d046-9 (34.203.13.78 | 10.12.10.103) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-8 (54.172.142.156 | 10.12.11.248) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-7 (34.228.17.170 | 10.12.11.18) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-6 (54.234.57.28 | 10.12.11.96) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-5 (54.164.179.131 | 10.12.11.88) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-4 (100.27.193.218 | 10.12.10.58) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-3 (54.163.214.164 | 10.12.8.50) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-27 (3.84.226.83 | 10.12.9.18) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-26 (54.226.14.242 | 10.12.10.27) (shards: -1)
- longevity-parallel-topology-schema--db-node-e3e9d046-25 (44.222.210.83 | 10.12.8.247) (shards: -1)
- longevity-parallel-topology-schema--db-node-e3e9d046-24 (44.220.141.12 | 10.12.11.247) (shards: -1)
- longevity-parallel-topology-schema--db-node-e3e9d046-23 (52.90.161.211 | 10.12.11.49) (shards: -1)
- longevity-parallel-topology-schema--db-node-e3e9d046-22 (34.229.162.175 | 10.12.9.246) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-21 (100.27.230.187 | 10.12.11.103) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-20 (54.87.51.148 | 10.12.11.115) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-2 (34.224.66.235 | 10.12.9.47) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-19 (54.235.2.128 | 10.12.11.127) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-18 (3.89.24.70 | 10.12.9.54) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-17 (3.88.100.32 | 10.12.8.210) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-16 (100.27.194.127 | 10.12.8.86) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-15 (54.147.138.100 | 10.12.8.195) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-14 (54.146.162.155 | 10.12.9.73) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-13 (3.91.21.67 | 10.12.9.143) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-12 (34.224.27.71 | 10.12.8.105) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-11 (3.88.154.30 | 10.12.11.166) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-10 (34.228.186.219 | 10.12.8.243) (shards: 7)
- longevity-parallel-topology-schema--db-node-e3e9d046-1 (54.82.87.95 | 10.12.8.143) (shards: 7)


OS / Image: `ami-0d95c4087d26503dd` (aws: undefined_region)

Test: `longevity-schema-topology-changes-12h-test`
Test id: `e3e9d046-164c-49aa-b1fb-19a53e1b6566`
Test name: `enterprise-2023.1/longevity/longevity-schema-topology-changes-12h-test`
Test config file(s):

- [longevity-parallel-schema-changes-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2d1cef1f9da0f3a751daa419b2d6c078676d446e/test-cases/longevity/longevity-parallel-schema-changes-12h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor e3e9d046-164c-49aa-b1fb-19a53e1b6566`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e3e9d046-164c-49aa-b1fb-19a53e1b6566)
- Show all stored logs command: `$ hydra investigate show-logs e3e9d046-164c-49aa-b1fb-19a53e1b6566`


## Logs:
- **db-cluster-e3e9d046.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e3e9d046-164c-49aa-b1fb-19a53e1b6566/20240707_185832/db-cluster-e3e9d046.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e3e9d046-164c-49aa-b1fb-19a53e1b6566/20240707_185832/db-cluster-e3e9d046.tar.gz)
- **sct-runner-events-e3e9d046.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e3e9d046-164c-49aa-b1fb-19a53e1b6566/20240707_185832/sct-runner-events-e3e9d046.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e3e9d046-164c-49aa-b1fb-19a53e1b6566/20240707_185832/sct-runner-events-e3e9d046.tar.gz)
- **sct-e3e9d046.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e3e9d046-164c-49aa-b1fb-19a53e1b6566/20240707_185832/sct-e3e9d046.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e3e9d046-164c-49aa-b1fb-19a53e1b6566/20240707_185832/sct-e3e9d046.log.tar.gz)
- **loader-set-e3e9d046.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e3e9d046-164c-49aa-b1fb-19a53e1b6566/20240707_185832/loader-set-e3e9d046.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e3e9d046-164c-49aa-b1fb-19a53e1b6566/20240707_185832/loader-set-e3e9d046.tar.gz)
- **monitor-set-e3e9d046.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e3e9d046-164c-49aa-b1fb-19a53e1b6566/20240707_185832/monitor-set-e3e9d046.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e3e9d046-164c-49aa-b1fb-19a53e1b6566/20240707_185832/monitor-set-e3e9d046.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-schema-topology-changes-12h-test/18/)
[Argus](https://argus.scylladb.com/test/079cddb4-4eac-4594-a2f0-8452dab5eb40/runs?additionalRuns[]=e3e9d046-164c-49aa-b1fb-19a53e1b6566)
</details>

**Comment by kbr-scylla** [comment]
> Jul 07 11:05:20.583593 longevity-parallel-topology-schema--db-node-e3e9d046-12 scylla[11291]:  [shard 0] raft - [464d7c46-6c64-44fd-a232-56e1321f4673] Transferring snapshot to 5f2e78c9-c1b2-47f3-87b4-048fd2589d0d failed with: raft::transport_error (Failed to execute virtual future<raft::snapshot_reply> service::raft_rpc::send_snapshot(raft::server_id, const raft::install_snapshot &, seastar::abort_source &) on leader 5f2e78c9-c1b2-47f3-87b4-048fd2589d0d: seastar::rpc::closed_error (connection is closed))

I assume `5f2e78c9-c1b2-47f3-87b4-048fd2589d0d`  was the newly bootstrapping node?

Then no, it's not the same issue. RPC to this node was interrupted because the node was killed. The cause was different, but it's still not a bug. It's expected for RPCs to killed node to fail. We can ignore this error **in this specific scenario**, i.e. node A boots, existing node B tries to send snapshot to A, A gets killed, B fails and reports snapshot transfer error.

**Comment by fruch** [comment]
addin @aleksbykov and @temichus  for awareness about this that should be filter in BootstrapStreamingError (which was built exactly of covering raft issue)

@juliayakovlev is looking if it's exist on SCT master, and if we are missing a backport

**Comment by patjed41** [comment]
This issue has already been fixed in dtest by ignoring the error message, see the comments above. We keep it open because we still haven't addressed the root cause.

The job with the failure reported in https://github.com/scylladb/scylladb/issues/15713#issuecomment-2740452857 is gone. This test failed often in the past, so I believe the fix was correct and this single failure after a year was actually a different failure. Sadly, I can't confirm it.

Regarding the root cause (described in https://github.com/scylladb/scylladb/issues/15713#issuecomment-1777350751), maybe it was fixed in the IP->host ID transition in some Scylla subsystems. @gleb-cloudius may know the answer.

cc @emdroid

**Comment by gleb-cloudius** [comment]
If Kamil's analysis  is correct (the issue is that old connection with the same IP is reused) then moving to host ids solved it. But the more general issues of dropped connection because of topology info change is not solved.

**Comment by patjed41** [comment]
So it looks like we can close this issue.
