### ISSUE TITLE
replace_address_test.py::TestReplaceAddress::test_replace_node_diff_ip fails with "storage_service/ownership cannot be used when a keyspace uses tablets" if tablets are enabled

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#17889]
neither `nodetool ring` nor `scylla nodetool ring` supports tablets.

```
ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-master/byo/dtest-byo/scylla/.ccm/scylla-repository/7d31093d4bde6753eb2d30aed46a1435869d52f9/share/cassandra/bin/nodetool -h 127.0.74.6 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy -Dcom.scylladb.apiPort=10000 ring exited with non-zero status; exit status: 1; 
stdout: nodetool: Scylla API server HTTP GET to URL '/storage_service/ownership/' failed: storage_service/ownership cannot be used when a keyspace uses tablets
See 'nodetool help' or 'nodetool help <command>'.
```

if keyspace is not specified in the command line, the java-based nodetool uses the RESTful API of `storage_service/ownership/` under the hood. but this API cannot be used if any of the keyspaces uses tablets.

likewise, even if keyspace is specified, `scylla nodetool ring` would fail as well if tablets are enabled, as `/storage_service/ownership/{}` requires the "cf" query parameter if the keyspace in question uses tablets.

**Comment by tchaikov** [comment]
cc @denesb

**Comment by tchaikov** [comment]
`nodetool status` suffers from the same problem.  in update_cluster_layout_tests.TestUpdateClusterLayout.test_change_node_ip_full_cluster_down, we have 
```
self = <update_cluster_layout_tests.TestUpdateClusterLayout object at 0x7faee8683b10>

    def test_change_node_ip_full_cluster_down(self):
        """
        Start 3 nodes
        Stop node 1 2 3
        Change IP address of node 1 2 3
        Start node 1 2 3 again
        Verify all nodes in the cluster notice other nodes use the new ip address
        """
        cluster = self.cluster
    
        cluster.set_configuration_options(values=self.default_config_options(), batch_commitlog=True)
        cluster.populate(3).start()
        node1, node2, node3 = cluster.nodelist()
    
        session = self.patient_cql_connection(node1)
        create_ks(session, "ks", 2)
        create_cf(session, "cf", read_repair=0.0, columns={"c1": "text", "c2": "text"})
        insert_c1c2(session, keys=range(1000), consistency=ConsistencyLevel.ONE)
    
        origin_hostid1 = node1.hostid()
        origin_hostid2 = node2.hostid()
        origin_hostid3 = node3.hostid()
    
        cluster.stop()
    
        ip_prefix = cluster.get_ipprefix()
        for node in cluster.nodelist():
            old_ip = node.address()
            lower_ip = int(old_ip.split(".")[-1]) + 10
            assert lower_ip < 255
            last = str(lower_ip)
            ip = f"{ip_prefix}{last}"
            logger.debug(f"Change IP address for {node.name} from {old_ip} to {ip}")
            node.set_configuration_options(values={"listen_address": ip, "rpc_address": ip, "api_address": ip})
            node.network_interfaces = {k: (ip, v[1]) for k, v in node.network_interfaces.items()}
    
        for node in cluster.nodelist():
            logger.debug(f"Start {node.name} again with ip address {node.address()}")
            node.start(wait_for_binary_proto=True, wait_other_notice=False)
    
        # Verify all nodes in the cluster see node3 is using the new ip address
        hostid1 = node1.hostid()
        hostid2 = node2.hostid()
        hostid3 = node3.hostid()
        ip1 = node1.address()
        ip2 = node2.address()
        ip3 = node3.address()
    
        for node in [node1, node2, node3]:
>           status = nodetool_status(node)

update_cluster_layout_tests.py:2615: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tools/status.py:34: in nodetool_status
    out = node.nodetool("status " + keyspace, True)[0]
../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:770: in nodetool
    return super().nodetool(cmd, capture_output, wait, timeout, verbose)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ccmlib.scylla_node.ScyllaNode object at 0x7faea0704050>
cmd = '-Dcom.scylladb.apiPort=10000 status ', capture_output = True, wait = True
timeout = None, verbose = True

    def nodetool(self, cmd, capture_output=True, wait=True, timeout=None, verbose=True):
        """
        Setting wait=False makes it impossible to detect errors,
        if capture_output is also False. wait=False allows us to return
        while nodetool is still running.
        When wait=True, timeout may be set to a number, in seconds,
        to limit how long the function will wait for nodetool to complete.
        """
        if capture_output and not wait:
            raise common.ArgumentError("Cannot set capture_output while wait is False.")
        env = self.get_env()
        if self.is_scylla() and not self.is_docker():
            host = self.address()
        else:
            host = 'localhost'
        nodetool = self.get_tool('nodetool')
    
        if not isinstance(nodetool, list):
            nodetool = [nodetool]
        # see https://www.oracle.com/java/technologies/javase/8u331-relnotes.html#JDK-8278972
        nodetool.extend(['-h', host, '-p', str(self.jmx_port), '-Dcom.sun.jndi.rmiURLParsing=legacy'])
        nodetool.extend(cmd.split())
        if verbose:
            self.debug(f"nodetool cmd={cmd} wait={wait} timeout={timeout}")
        if capture_output:
            p = subprocess.Popen(nodetool, universal_newlines=True, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            stdout, stderr = p.communicate(timeout=timeout)
        else:
            p = subprocess.Popen(nodetool, env=env, universal_newlines=True)
            stdout, stderr = None, None
    
        if wait:
            exit_status = p.wait(timeout=timeout)
            if exit_status != 0:
>               raise NodetoolError(" ".join(nodetool), exit_status, stdout, stderr)
E               ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-master/byo/dtest-byo/scylla/.ccm/scylla-repository/7d31093d4bde6753eb2d30aed46a1435869d52f9/share/cassandra/bin/nodetool -h 127.0.98.11 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy -Dcom.scylladb.apiPort=10000 status exited with non-zero status; exit status: 1; 
E               stdout: nodetool: Scylla API server HTTP GET to URL '/storage_service/ownership/' failed: storage_service/ownership cannot be used when a keyspace uses tablets
E               See 'nodetool help' or 'nodetool help <command>'.

../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:845: ToolError

```

**Comment by tchaikov** [comment]
the `status` subcommand should be fixed by #17827

**Comment by denesb** [comment]
@tchaikov can we close this now? Both status and describering should now support tablets.

**Comment by denesb** [comment]
And they should be available for use in dtests.

**Comment by tchaikov** [comment]
@denesb i was using java-based tools for testing, because i was testing from the source tree. only the reloc package points to the native tool. and the change in ccm hasn't landed. that's why i am seeing this issue even i am testing with latest scylla, dtest and ccm. sorry for the false alarm. closing.

**Comment by bhalevy** [comment]
nodetool ring still doesn't support a `cf` parameter, only `keyspace` and therefore it is not suitable for tablets
also, this needs to be integrated with replace_address_test dtest get_sorted_tokens() function.
See for example https://jenkins.scylladb.com/job/scylla-master/job/tablets/job/gating-dtest-release-with-tablets/46/testReport/replace_address_test/TestReplaceAddress/FullDtest___full_split003___test_replace_node_diff_ip_use_endpoint_rbo_disabled_/
```
self = <replace_address_test.TestReplaceAddress object at 0x7f4c9c76dd10>
use_host_id = False

    @pytest.mark.parametrize("use_host_id", [True, False], ids=["use_host_id", "use_endpoint"])
    @pytest.mark.skip_if(with_feature("tablets") & issue_open("#17889"))
    def test_replace_node_diff_ip(self, use_host_id: bool):
        logger.info("Starting cluster with 5 nodes.")
        cluster = self.cluster
        cluster.populate(5).start(wait_for_binary_proto=True)
        node1, node2, node3, node4, node5 = cluster.nodelist()
    
        node5_tokens = self.get_sorted_tokens(node5)
    
        session = self.patient_cql_connection(node5)
        create_ks(session, "ks", 3)
        create_cf(session, "cf", read_repair=0.0, columns={"c1": "text", "c2": "text"})
        insert_c1c2(session, keys=range(1000), consistency=ConsistencyLevel.ALL)
    
        node5_hostid = node5.hostid()
        ip5 = node5.address()
        node5.stop()
    
        logger.info("Starting node 6 to replace node 5")
        node6 = cluster.new_node(6, auto_bootstrap=True, is_seed=False)
        replace_node_host_id = node5_hostid if use_host_id else None
        replace_address = ip5 if not use_host_id else None
        node6.start(wait_for_binary_proto=True, replace_node_host_id=replace_node_host_id, replace_address=replace_address)
    
        if "consistent-topology-changes" in self.scylla_features:
            log_message_to_wait = f"gossip - Finished to force remove node {ip5}"
        else:
            log_message_to_wait = f"FatClient .*{ip5} has been silent for .*ms, removing from gossip"
        for node in [node1, node2, node3, node4, node6]:
            node.watch_log_for(log_message_to_wait)
    
        logger.info("Verifying tokens migrated successfully")
>       moved_tokens_list = self.get_sorted_tokens(node6)

replace_address_test.py:806: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
replace_address_test.py:97: in get_sorted_tokens
    ring_lines = [line for line in node.nodetool("ring")[0].splitlines() if address in line]
../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:796: in nodetool
    return super().nodetool(cmd, capture_output, wait, timeout, verbose)
../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:866: in nodetool
    return self._do_run_nodetool(nodetool, capture_output, wait, timeout, verbose)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ccmlib.scylla_node.ScyllaNode object at 0x7f4c3c5ab490>
nodetool = ['/jenkins/workspace/scylla-master/tablets/gating-dtest-release-with-tablets/scylla/.ccm/scylla-repository/d8313dda43d...85d4ef9030/share/cassandra/bin/nodetool', '-h', '127.0.26.6', '-p', '7199', '-Dcom.sun.jndi.rmiURLParsing=legacy', ...]
capture_output = True, wait = True, timeout = None, verbose = True

    def _do_run_nodetool(self, nodetool, capture_output=True, wait=True, timeout=None, verbose=True):
        if capture_output and not wait:
            raise common.ArgumentError("Cannot set capture_output while wait is False.")
        env = self.get_env()
        if verbose:
            self.debug(f"nodetool cmd={nodetool} wait={wait} timeout={timeout}")
        if capture_output:
            p = subprocess.Popen(nodetool, universal_newlines=True, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            stdout, stderr = p.communicate(timeout=timeout)
        else:
            p = subprocess.Popen(nodetool, env=env, universal_newlines=True)
            stdout, stderr = None, None
    
        if wait:
            exit_status = p.wait(timeout=timeout)
            if exit_status != 0:
>               raise NodetoolError(" ".join(nodetool), exit_status, stdout, stderr)
E               ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-master/tablets/gating-dtest-release-with-tablets/scylla/.ccm/scylla-repository/d8313dda43d7014460891e7da7dab785d4ef9030/share/cassandra/bin/nodetool -h 127.0.26.6 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy -Dcom.scylladb.apiPort=10000 ring exited with non-zero status; exit status: 1; 
E               stdout: nodetool: Scylla API server HTTP GET to URL '/storage_service/ownership/' failed: storage_service/ownership cannot be used when a keyspace uses tablets
E               See 'nodetool help' or 'nodetool help <command>'.

../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:827: ToolError
```

**Comment by denesb** [comment]
> The native implementation does support a table parameter, since the very beginning, see [8fcb4ed](https://github.com/scylladb/scylladb/commit/8fcb4ed707b5f923ec11e3bcbb85bd623c1adf7d). Based on the logs, the test ended up using the Java nodetool, which indeed doesn't support the table parameter.

I mixed up `ring` with `describering`. Indeed, `ring` does not yet support a table parameter. I will send a PR.

**Comment by bhalevy** [comment]
> > The native implementation does support a table parameter, since the very beginning, see [8fcb4ed](https://github.com/scylladb/scylladb/commit/8fcb4ed707b5f923ec11e3bcbb85bd623c1adf7d). Based on the logs, the test ended up using the Java nodetool, which indeed doesn't support the table parameter.
> 
> I mixed up `ring` with `describering`. Indeed, `ring` does not yet support a table parameter. I will send a PR.

@denesb please mark it as fixing https://github.com/scylladb/scylladb/issues/18474

**Comment by denesb** [comment]
While working on this, I discovered that even with the added `table` parameter, `nodetool ring` (as well as nodetool status) uses the vnode tokens, even when parametrized with a tablet table. This makes no sense. Not so much an issue for `status` (we just print the number of tokens), but for ring the output ends up being bogus for the given input.
