### ISSUE TITLE
Per-table tablet load is imbalanced after series of splits and merges

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#22982]
The images below demonstrate the problem. We start with per-table balance. The purple table is first split then merged. Per-table balance is broken. 

<img src="https://github.com/user-attachments/assets/5b732061-ac4c-4f37-a5d9-e886725b1d0f" width="200">

<img src="https://github.com/user-attachments/assets/1ead4549-1b73-4f3e-b5cd-77c66dd5540b" width="200">

<img src="https://github.com/user-attachments/assets/8ed5eb6d-8490-4c9d-afa2-4c10a728aabd" width="200">

Note that other tables are also split and merged to keep the per-shard tablet count constant. This test was performed on https://github.com/scylladb/scylladb/pull/22522 which triggers splits and merges.

We end up with bad per-table balance, because the load balancer doesn't have an algorithm which explicitly evaluates per-table balance and tries to even it out. Per-table balancing is considered on-the-fly when choosing candidates during migration which tries to achieve global per-shard balance.

**Comment by tgrabiec** [comment]
\cc @bhalevy @nodep @avikivity

**Comment by avikivity** [comment]
When we migrate for merge, do we consider per-table balance?

Regardless we should have a per-table balance as a separate goal, so even if per-shard balance is achieved we should continue migration until per-table balance is achieved as well.

**Comment by tgrabiec** [comment]
> When we migrate for merge, do we consider per-table balance?

No, we migrate to match the sibling replica list, and don't make compensating migrations for table balance. That can happen during merge as part of regular load balancing if global balance is broken by merge migrations.

**Comment by raphaelsc** [comment]
> > When we migrate for merge, do we consider per-table balance?
> 
> No, we migrate to match the sibling replica list, and don't make compensating migrations for table balance. 

Merge is lower in priority, so once balancer is also triggered by table imbalance, my understanding is that this should be fixed since balancer is allowed (today) in between co-location decisions, right? Do we have to exchange tablets (in a swap like migration) to not temporarily cause shard imbalance? With 100 replicas/shard, that's ~2% overcommitted though.

**Comment by tgrabiec** [comment]
QA ran into a scenario which falls under this problem, and causes significant per-table imbalance for one of the
tables (some nodes have half the per-shard utilization as other nodes).

3 racks, RF=3, initial_tablets=1024
We start with one large instance per rack and 1 table (table1).
Then add a small instance to each rack. Wait for rebalance.
Add another table (table2).

This will trigger merge of the old table due to per-shard tablet count goal.
The new table will not be merged, it will use smaller tablet count from the beginning.
Small instances are overloaded with table2 tablets due to https://github.com/scylladb/scylladb/issues/23378.

Co-locating migrations of table1 are done concurrently with load-balancing migrations of table2, and table1 balance will be broken because even-numbered tablets of table1 don't have an even replica load distribution, large instances are loaded more.
Because small instances are overloaded, load balancer will keep moving tablets of table2 to compensate for the global imbalance, which will also compensate the global imbalance made by merge, and table1 balance will not be fixed. The imbalance of table1 goes in the opposite direction, so fixing global balance goes against fixing table1 imbalance, so table-aware balancing logic we have cannot solve this. The algorithm proposed in https://github.com/scylladb/scylladb/pull/20118 would.

If table2 was evenly balanced, then the problem wouldn't happen because co-locating migrations of table1
which break the table1 balance will also break the global balance, and regular load-balancing will fix global balance by fixing table1 balance. 

Reproducer introduced here: https://github.com/scylladb/scylladb/pull/23477

**Comment by tgrabiec** [comment]
Another scenario: https://github.com/scylladb/scylladb/issues/23631#issuecomment-2789776913

1) Scale out adds new nodes to each tack
2) table is created - all tablets are allocated to new nodes
3) rebalancing moves tablets from old nodes to new nodes - table balance for the new table is not fixed

**Comment by dani-tweig** [comment]
Closing this issue as it was moved to Jira.
Please continue the thread in https://scylladb.atlassian.net/browse/SCYLLADB-1972
