### ISSUE TITLE
calculate_schema_digest() is very inefficient when there are many tables, even if deleted

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#7620]
This is a spin-off from issue #7594 (I'm not sure the issue I describe here is the *only* problem in that issue).

Even in a trivial one-node setup, when you repeatedly create and delete a table with a random name (a different name every time), these iterations become slower and slower over time. The following Alternator test is an easy reproducer:

```python
def test_many_create_and_delete_table(dynamodb):
    for i in range(2000):
        s = time.time()
        create_and_delete_table(dynamodb, test_table_name())
        e = time.time()
        print("{}: {}", i, e-s)
```
  
In this test, the first few creation/remove pair take 0.5 seconds, and this time steadily increases - the 100th iteration takes 1 second, and the 400th takes 2 seconds. The 700th iteration takes 3 seconds. The 1000th iteration takes 4 seconds.

Adding a bunch of timings printouts to Scylla, I discovered that the culprit is `calculate_schema_digest()`, which takes 25ms when there are just a few default tables, and 500ms after 500 iterations of the above test.

Note that after 500 iterations we don't actually have 500 tables (they have all been deleted), but the "tables" system table does contain 500 tombstones, one for each deleted table (and we have the same also in the keyspaces). Somehow these 500 tombstones add almost 500ms to the `calculate_schema_digest()`. This is much too much taking almost a full millisecond for hashing each tombstone is unreasonable. (By the way, should tombstones be hashed at all?)

Update: Note that Alternator doesn't create and delete all these different tables in the same keyspace - it actually creates and deletes a separate keyspace for each table. So the "tables" system table has partition tombstones (each partition is a keyspace), not row tombstones. This may make a difference?

**Comment by nyh** [comment]
May be related to #6376, which also involves `calculate_schema_digest()` performance when there are many tables (in that issue - 5000 tables, all of them actual tables, not tombstones).

**Comment by elcallio** [comment]
Since calculate_schema_digest literally reads the full set of all schema mutations for a given set of features (not just the schema we are adding/changing), it is perhaps not surprising it becomes slower with every schema added. 
Could maybe optimize it for adding schemas by keeping track of previous hash state and just feed new mutations, but that probably breaks on ordering. And also seems dangerous.

**Comment by avikivity** [comment]
@tgrabiec proposed hashing the hashes of individual tables. This way the full version depends on all the tables, but only on their hashes, not their entire contents.

**Comment by nyh** [comment]
> @tgrabiec proposed hashing the hashes of individual tables. This way the full version depends on all the tables, but only on their hashes, not their entire contents.

I still don't understand what this code may possibly be doing to explain how hashing a 53-byte tombstone, even seven times and even with the worst possible hashing algorithm, can take a whole milisecond. I am guessing there may be a quadratic algorithm somewhere - may we are reading an entire file (maybe more than once) just to checksum one partition. I am not familiar at all with this code, so I don't know where this is coming from.

**Comment by tgrabiec** [comment]
@nyh Tombstones are not hashed (see compact_for_schema_digest). They are still read though. I suspect that it's slow not due to hashing, but because of reading of mutations from storage. Is compaction keeping up? Maybe we have to many sstables.

**Comment by tgrabiec** [comment]
Another thing is that cache doesn't compact, so if we read from cache, we read mutations for the deleted tables too. You can verify this theory by running with cache disabled.

**Comment by nyh** [comment]
> @nyh Tombstones are not hashed (see compact_for_schema_digest). They are still read though. I suspect that it's slow not due to hashing, but because of reading of mutations from storage. Is compaction keeping up? Maybe we have to many sstables.

Compaction is keeping up well - we have usually just one sstable for the keyspaces and tables system tables.

**Comment by nyh** [comment]
The `calculate_schema_digest()` has a main loop over all schema tables. I measured the time of the processing over these individual tables.  For example, after about 400 iterations of creations and deletions, `calculate_schema_digest()` now takes 400ms. The "keyspaces" table takes 40ms of it, "tables" takes 80ms, "columns" takes 70ms, "views" takes just 14ms, etc.

I measured that the vast majority of the time spent on each of these tables is in the **`db::system_keyspace::query_mutations(proxy, NAME, table)`**. So it's not even checksumming, it's not tombstone, nothing - it's just query_mutations. This specific call becomes increasingly slow. It makes no sense that reading a 20 KB (!) file like the "tables" table takes 80ms and continuously increasing....

**Comment by avikivity** [comment]
Maybe there's a bunch of tombstones in cache.

**Comment by nyh** [comment]
> Maybe there's a bunch of tombstones in cache.

I'll take a look at it more carefully (Tomek also suggested this possibility), but one of the first experiment I did was to make sure the slowness does not go away after restarting Scylla. So it can't be something which remains in memory which shouldn't be like excess stuff in the cache. The cache may contain the 500 tombstones (after 500 iterations) we have on disk for the deleted tables, but that's it.

**Comment by nyh** [comment]
As I'm continuing to drill in on what takes time, another data point - the function `query_mutations()` in `db/system_keyspace.cc`, running on the "tables" system table, takes 3ms in the beginning, and a whopping 80ms after 500 iterations, when the "tables" table has a measly 500 tombstones and around 20 KB total on-size disk in two sstables.
Yes, obviously reading 500 tombstones should take more than none, but not 80ms.

**Comment by tgrabiec** [comment]
Maybe it's a combination of https://github.com/scylladb/scylla/issues/2890 and the incremental nature of scans which use exponentially increasing token ranges to query data.

**Comment by tgrabiec** [comment]
Is this with a single shard?

**Comment by avikivity** [comment]
Switching local tables to use a sharder that always selects shard 0 would simplify things. Or perhaps a sharder that has murmur3_ignore_msb_bits = 0, so that all shards are in use, but a single linear scan over all shards is enough.

murmur3_ignore_msb_bits was introduced to combat aliasing with vnodes, but there are no vnodes for local tables.

**Comment by tgrabiec** [comment]
Related sharder bug: https://github.com/scylladb/scylla/issues/7642

**Comment by nyh** [comment]
@tgrabiec my test is using two shards.

I'm going down a rabbit hole of code I don't understand, and what worries me more is that all this `query_mutations_locally()` code seems to be quite distinct from all the other query code we normally use. Why can't we use a *normal* scan? Why do we need to read "mutations" - including tombstones, do we need those tombstones for the hash function(I think we don't!). Who's the expert on this code? 'git blame' on the `query_mutations_locally()` function shows every line was written by a different person :-)

One note about all the sharding problem guesses mentioned above (I'll take a look at the issues you guys mentioned) - the time `query_mutations_locally()` takes is clearly proportional to the number of partitions (most of them tombstones!!) being scanned, not the number of shards or vnodes. So it's not the "usual" problem of having to repeat the query on a lot of shards (this may explain why we get to 3ms just to read the empty table, but not why we grow to 80ms when we add 500 tombstones to the table).

**Comment by tgrabiec** [comment]
On Wed, Nov 18, 2020 at 11:59 AM nyh <notifications@github.com> wrote:

> @tgrabiec <https://github.com/tgrabiec> my test is using two shards.
>
Do you get better results with a single shard?

> I'm going down a rabbit hole of code I don't understand, and what worries
> me more is that all this query_mutations_locally() code seems to be quite
> distinct from all the other query code we normally use. Why can't we use a
> *normal* scan? Why do we need to read "mutations" - including tombstones,
> do we need those tombstones for the hash function(I think we don't!). Who's
> the expert on this code? 'git blame' on the query_mutations_locally()
> function shows every line was written by a different person :-)
>
query_mutations_locally() is what would be called eventually by a regular
query as well. We simply bypass unneeded layers (storage_proxy).

We query mutations because we take timestamps into account.

Currently, there's no way to query mutations without tombstones at the
replica level. We query mutations and then compact them to drop tombstones.

Single-shard data queries can query for data only, but they also do that by
querying for mutations and compacting on-the-fly.

Maybe try running with trace-level logging around the digest read on the
"cache" and "sstable" logger to see if we're getting excessive activity for
a single read. Compare that with the state with no tombstones.

One note about all the sharding problem guesses mentioned above (I'll take
> a look at the issues you guys mentioned) - the time
> query_mutations_locally() takes is clearly proportional to the number of
> partitions (most of them tombstones!!) being scanned, not the number of
> shards or vnodes. So it's not the "usual" problem of having to repeat the
> query on a lot of shards (this may explain why we get to 3ms just to read
> the empty table, but not why we grow to 80ms when we add 500 tombstones to
> the table).
>

**Comment by tgrabiec** [comment]
On Wed, Nov 18, 2020 at 12:25 PM Tomasz Grabiec <tgrabiec@gmail.com> wrote:

>
>
> On Wed, Nov 18, 2020 at 11:59 AM nyh <notifications@github.com> wrote:
>
>> @tgrabiec <https://github.com/tgrabiec> my test is using two shards.
>>
> Do you get better results with a single shard?
>
>> I'm going down a rabbit hole of code I don't understand, and what worries
>> me more is that all this query_mutations_locally() code seems to be
>> quite distinct from all the other query code we normally use. Why can't we
>> use a *normal* scan? Why do we need to read "mutations" - including
>> tombstones, do we need those tombstones for the hash function(I think we
>> don't!). Who's the expert on this code? 'git blame' on the
>> query_mutations_locally() function shows every line was written by a
>> different person :-)
>>
> query_mutations_locally() is what would be called eventually by a regular
> query as well. We simply bypass unneeded layers (storage_proxy).
>
> We query mutations because we take timestamps into account.
>
> Currently, there's no way to query mutations without tombstones at the
> replica level. We query mutations and then compact them to drop tombstones.
>
> Single-shard data queries can query for data only, but they also do that
> by querying for mutations and compacting on-the-fly.
>
> Maybe try running with trace-level logging around the digest read on the
> "cache" and "sstable" logger to see if we're getting excessive activity for
> a single read. Compare that with the state with no tombstones.
>
> One note about all the sharding problem guesses mentioned above (I'll take
>> a look at the issues you guys mentioned) - the time
>> query_mutations_locally() takes is clearly proportional to the number of
>> partitions (most of them tombstones!!) being scanned, not the number of
>> shards or vnodes. So it's not the "usual" problem of having to repeat the
>> query on a lot of shards (this may explain why we get to 3ms just to read
>> the empty table, but not why we grow to 80ms when we add 500 tombstones to
>> the table).
>>
>
>
CQL tracing could also help (you'd have to manually cook a trace_info).

**Comment by nyh** [comment]
> Do you get better results with a single shard?

I tested now, and the answer is no. The absolute numbers are somewhat lower, but they still clearly grow as you add these tombstones (and again, I'm not talking about millions here, just a few hundreds add tens of milliseconds to a scan).

**Comment by nyh** [comment]
To other datapoints:
1. The slowness, which I mentioned already is proportional to the number of partitions or tombstones (in my case it's the same), is NOT related to the number of vnodes. I was actually using num_tokens=16, but increasing it to 256 doesn't change anything.
2. setting --murmur3-partitioner-ignore-msb-bits=0 seems to speed things up a bit, but the slowdown is still significant: If before I needed 100 tombstones to slow down table creation to a full second, now I need 200. Something is still very wrong.

I'm down the rabit hole to `do_query_mutations()` which slows down. I'm so deep in the hole now that I can't see the entrance, nor the end. And I guess it would be pointless to note that none of these functions has any comment on why it exists or how it works :-(

**Comment by kostja** [comment]
Now that we have started to reuse scylla among many tests in test.py this becomes a serious hindrance. E.g. it makes it hard to debug flaky tests, since each repeat is taking increasingly more time:

[41/50]      cql     debug  [ PASS ] cdc_with_lwt_test.41 3.99s
[42/50]      cql     debug  [ FAIL ] cdc_with_lwt_test.42 4.28s
[43/50]      cql     debug  [ PASS ] cdc_with_lwt_test.43 4.33s
[44/50]      cql     debug  [ PASS ] cdc_with_lwt_test.44 4.15s
[45/50]      cql     debug  [ FAIL ] cdc_with_lwt_test.45 4.40s
[46/50]      cql     debug  [ PASS ] cdc_with_lwt_test.46 4.30s
[47/50]      cql     debug  [ PASS ] cdc_with_lwt_test.47 4.52s
[48/50]      cql     debug  [ FAIL ] cdc_with_lwt_test.48 4.61s
[49/50]      cql     debug  [ PASS ] cdc_with_lwt_test.49 4.40s

I was able to crash scylla with ~5000 repeats (finding the root cause of the crash is also difficult since repeating the 5000 repeat is a feat right now thanks to this issue).

**Comment by nyh** [comment]
By the way, for anybody looking for a **workaround** for this bug (though we really need to solve it!) - the problem happens when you create and delete a keyspace or a table many times, but use a random name each time. The workaround is simply not to use so many **different** random names:

You can see an example workaround in `test/cql-pytest/cassandra_tests/porting.py`: Those CQL tests create a gazillion different tables, so they had this problem when each test picked a different random name for the table. The solution is to create a cache of deleted tables' **names**. The `create_table()` function, when it need to create a table, it first tries to recycle the name of an old already-deleted table. If there's no such name in the cache, it invents a random one.

**Comment by nyh** [comment]
> May have been fixed by [94f9109](https://github.com/scylladb/scylla/commit/94f9109beaa0c841831acc9f2ca744efcf8adcf1)

No, that's not it - I tested the version before this commit (and before the entire merge that includes it) - and it already gives reasonable performance: Running my Scylla alternator test creating and deleting random-named tables, the first iteration: 0.015 seconds, 500th iteration: 0.053 seconds.

So the serious bug was somehow solved earlier.

I'll try to bisect now!

By the way, this specific change should not have made a difference so I'm not surprised it made a diffence. I can understand the patch you pointed to could improve the performance of each iteraction (if it involves fewer flushes), but why would it make a difference on how much the 500th iteration is slower than the 1st iteration? Don't both of them involve the same number of memtable flushes?

**Comment by nyh** [comment]
By the way, just one month ago, in dc5c9321fee9e307c3e95c3882564b0053614a98, I committed a fix to cql-pytest that will recycle the same table names (just the names! not the tables!) instead of inventing new table names all the time, and it made a big difference (check out the numbers in that commit) - which still existed one month ago. This  can be another way to reproduce this issue, by testing with and without that commit.

**Comment by avikivity** [comment]
> > May have been fixed by [94f9109](https://github.com/scylladb/scylla/commit/94f9109beaa0c841831acc9f2ca744efcf8adcf1)
> 
> No, that's not it - I tested the version before this commit (and before the entire merge that includes it) - and it already gives reasonable performance: Running my Scylla alternator test creating and deleting random-named tables, the first iteration: 0.015 seconds, 500th iteration: 0.053 seconds.
> 
> So the serious bug was somehow solved earlier.
> 
> I'll try to bisect now!
> 
> By the way, this specific change should not have made a difference so I'm not surprised it didn't make a diffence. I can understand the patch you pointed to could improve the performance of each iteraction (if it involves fewer flushes), but why would it make a difference on how much the 500th iteration is slower than the 1st iteration? Don't both of them involve the same number of memtable flushes?

Not arguing that it's not the fixer, but my thinking was that with memtables/cache holding data+tombstones they have to do much more work when calculating the digest compared to when they just hold the tombstones. It's still true, but apparently not critically so.

**Comment by kostja** [comment]
Fixed in the latest master by 
commit 4bd4aa2e887278c4912f65b80548faaad4e05951
Merge: 665e8c1a23 169025d9b4
Author: Botond Dénes <bdenes@scylladb.com>
Date:   Wed Jun 15 18:12:42 2022 +0300

    Merge 'memtable, cache: Eagerly compact data with tombstones' from Tomasz Grabiec
    
    When memtable receives a tombstone it can happen under some workloads
    that it covers data which is still in the memtable. Some workloads may
    insert and delete data within a short time frame. We could reduce the
    rate of memtable flushes if we eagerly drop tombstoned data.
    
    One workload which benefits is the raft log. It stores a row for each
    uncommitted raft entry. When entries are committed they are
    deleted. So the live set is expected to be short under normal
    conditions.
    
    Fixes #652.
    
    Closes #10807
    
    * github.com:scylladb/scylla:
      memtable: Add counters for tombstone compaction
      memtable, cache: Eagerly compact data with tombstones
      memtable: Subtract from flushed memory when cleaning
      mvcc: Introduce apply_resume to hold state for partition version merging
      test: mutation: Compare against compacted mutations
      compacting_reader: Drop irrelevant tombstones
      mutation_partition: Extract deletable_row::compact_and_expire()
      mvcc: Apply mutations in memtable with preemption enabled
      test: memtable: Make failed_flush_prevents_writes() immune to backg

**Comment by nyh** [comment]
> Fixed in the latest master by commit [4bd4aa2](https://github.com/scylladb/scylla/commit/4bd4aa2e887278c4912f65b80548faaad4e05951) Merge: [665e8c1](https://github.com/scylladb/scylla/commit/665e8c1a23dc49743bc35550997b756c10745b3d) [169025d](https://github.com/scylladb/scylla/commit/169025d9b46797891ba4c998aeecd4f912816cd5) Author: Botond Dénes Date: Wed Jun 15 18:12:42 2022 +0300
> 
> ```
> Merge 'memtable, cache: Eagerly compact data with tombstones' from Tomasz Grabiec
> 
> When memtable receives a tombstone it can happen under some workloads
> that it covers data which is still in the memtable. Some workloads may
> insert and delete data within a short time frame. We could reduce the
> rate of memtable flushes if we eagerly drop tombstoned data.
> 
> One workload which benefits is the raft log. It stores a row for each
> uncommitted raft entry. When entries are committed they are
> deleted. So the live set is expected to be short under normal
> conditions.
> 
> Fixes #652.
> 
> Closes #10807
> 
> * github.com:scylladb/scylla:
>   memtable: Add counters for tombstone compaction
>   memtable, cache: Eagerly compact data with tombstones
>   memtable: Subtract from flushed memory when cleaning
>   mvcc: Introduce apply_resume to hold state for partition version merging
>   test: mutation: Compare against compacted mutations
>   compacting_reader: Drop irrelevant tombstones
>   mutation_partition: Extract deletable_row::compact_and_expire()
>   mvcc: Apply mutations in memtable with preemption enabled
>   test: memtable: Make failed_flush_prevents_writes() immune to backg
> ```

@kostja were you actually able to demonstrate that this patch fixed something (tried some workload, and it was very slow / crashed before this patch and after this patch worked well?)

**Comment by nyh** [comment]
I don't think this bug was fixed. I retried the experiment describe in https://github.com/scylladb/scylla/commit/dc5c9321fee9e307c3e95c3882564b0053614a98 on master, and the problem is not solved:

What I describe there is running the same set of tests 100 times (`test/cql-pytest/run --count N test_filtering.py`, each time picking different random table names - revert that commit to force different random table names).

On master right now, using different random table names takes 98 seconds. With that commit (to reuse the same table names) the total time is 39 seconds.

This is very closes to the times seen a month ago, and suggest that it wasn't fixed by this recent patch, and wasn't fixed at all.

@kostja can you share a different benchmark which convinced you the bug was fixed?

**Comment by kostja** [comment]
Yes we were able to verify it's no longer reproducible. If you were trying a different keyspace, you may see the impact of the growing number of sstables on the test, which is fixed by a different patch (having a separate commit log for schema tables).

**Comment by nyh** [comment]
> Yes we were able to verify it's no longer reproducible.

How? What did you test and how?

> If you were trying a different keyspace, you may see the impact of the growing number of sstables on the test, which is fixed by a different patch (having a separate commit log for schema tables).

No, the test I mentioned above involved creating just one keyspace once, and then running about a thousand tests each of them creating a random-named table (different name each time) in that single keyspace and then deleting it. (I gave the command line above, compare master (all tables recycle the same name - but the table still gets created and deleted a thousand times) to master with dc5c9321fee9e307c3e95c3882564b0053614a98 reverted (so tables use a different random name).

I'll try later to see how I can reproduce this problem in a more stand-alone, single, test.

**Comment by gusev-p** [comment]
> 3.5 seconds for creating and dropping one table is absolutely terrible, and suggests the bug still exists. Are you sure that for the first table it took you 0.5 seconds? That's also a lot.

It seems that I had some problems with the environment (disks/SSD?) when I ran that test, those problems added the big random delays and masked the initial issue. I'll try to retest.

**Comment by nyh** [comment]
Here's a simple stand-alone test (in cql-pytest framework, run with `test/cql-ytest/run -vs test_try.py |& less`) that demonstrates the issue still exists:

```python
import pytest
import time
from util import unique_name

def test_many_create_and_delete_table(cql, test_keyspace):
    for i in range(3000):
        s = time.time()
        table_name = f"{test_keyspace}.{unique_name()}"
        cql.execute(f"create table {table_name} (p int primary key, v int)")
        cql.execute(f"drop table {table_name}")
        e = time.time()
        print("{}: {}", i, e-s)
```

On my laptop, the first create/drop pairs take roughly 0.015 second each, while after 3000 random-named tables were created and deleted, the 3000th iteration takes around 0.15 seconds each. That's 10 times slower, meaning that 90% of the work that the 3000th iteration does is somehow related to those long-ago-deleted tables.

I just discovered a new (?) problem which may explain part of the slowdown :-( @bhalevy are you aware of the following?
For every deleted table, its directory stays behind with empty "staging" and "upload" subdirectories. This slows down the filesystem operations on the keyspace directory, which now has thousands of subdirectories. I doubt this explains the 0.14 second overhead in the 3000th table creation, but I'll look at that direction as well.

**Comment by bhalevy** [comment]
Typically auto-snapshot will take a snapshot of each to-be-deleted table so I presumed this was the cause that the table directory was left behind. I wasn't aware that it is left behind also with auto_snapshot=false.

**Comment by nyh** [comment]
I continued running the aforementioned test `test_many_create_and_delete_table` for more iterations: Whereas table create/drop pair took 0.015 seconds on the first iteration, and 0.15 seconds on the 3000th iteration, it took 0.25 seconds on the 5000th iteration, and  0.43 seconds in the 10000th iteration.

So this bug was definitely not fixed - not by the specific commit mentioned by @avikivity or @kostja and not by any commit, because it still exists on master.

Note that the number of iterations (different-named tables created and deleted) in these examples, like N=10000, are not huge. A table with 10,000 tombstones is still tiny, and shouldn't take 0.4 seconds to read from. We're doing something very wrong, I just don't know what.

That being said, I don't know to explain why the numbers on my current tests are orders of magnitude better than the ones in my original report at the top of this issue. There is still a clear linear growth of the time of the Nth iteration, which should have been constant time, but the speed of the 1st and Nth iteration are both much, much, faster than in my first report. I admit that if those were the numbers that I saw in my original report, maybe I wouldn't have even noticed it. But I'm lucky that I did, because knowing this bug is still important - for example in https://github.com/scylladb/scylla/commit/dc5c9321fee9e307c3e95c3882564b0053614a98 I used the awareness of this bug to considerably speed up testing.

**Comment by avikivity** [comment]
> > 3.5 seconds for creating and dropping one table is absolutely terrible, and suggests the bug still exists. Are you sure that for the first table it took you 0.5 seconds? That's also a lot.
> 
> It seems that I had some problems with the environment (disks/SSD?) when I ran that test, those problems added the big random delays and masked the initial issue. I'll try to retest.

On consumer SSDs, --kernel-page-cache and --unsafe-bypass-fsync are recommended (it's still going to be bad).

**Comment by gusev-p** [comment]
> Here's a simple stand-alone test (in cql-pytest framework, run with `test/cql-ytest/run -vs test_try.py |& less`) that demonstrates the issue still exists:
> 
> ```python
> import pytest
> import time
> from util import unique_name
> 
> def test_many_create_and_delete_table(cql, test_keyspace):
>     for i in range(3000):
>         s = time.time()
>         table_name = f"{test_keyspace}.{unique_name()}"
>         cql.execute(f"create table {table_name} (p int primary key, v int)")
>         cql.execute(f"drop table {table_name}")
>         e = time.time()
>         print("{}: {}", i, e-s)
> ```
> 
> On my laptop, the first create/drop pairs take roughly 0.015 second each, while after 3000 random-named tables were created and deleted, the 3000th iteration takes around 0.15 seconds each. That's 10 times slower, meaning that 90% of the work that the 3000th iteration does is somehow related to those long-ago-deleted tables.
> 
> If you move the `table_name=` a few lines up before the loop, so that the same-named table is created and deleted again and again, the 3000th iteration now takes 0.025 seconds - which is only a bit worse than 0.015 and not as bad as 0.15 we saw with different-named tables. I think I have an explanation for that 0.025 - see #10896 - but it is a much smaller effect than the one I reported in this bug, where having not-so-many (just 3000!) deleted table names greatly slows down further schema operations.

I reproduced the problem:
```
pytest test_try.py::test_many_create_and_delete_table -s &> ~/logg11

============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.11.0, pluggy-0.13.1
rootdir: /home/fedora/scylla/test/cql-pytest, configfile: pytest.ini
plugins: repeat-0.9.1, asyncio-0.14.0
collected 1 item

test_try.py {}: {} 0 0.0301058292388916
{}: {} 1 0.029410839080810547
{}: {} 2 0.029661178588867188
{}: {} 3 0.029175519943237305
{}: {} 4 0.03025984764099121
...
{}: {} 2996 0.1554245948791504
{}: {} 2997 0.1553642749786377
{}: {} 2998 0.15498065948486328
{}: {} 2999 0.1560671329498291
```
I'll explore it further.

**Comment by gusev-p** [comment]
1. I ran the test with logs several times, the increase in timings is entirely inside `calculate_schema_digest`
2. more specifically, we see the following:
```
first (1) test iteration
    {},{}: {} {} {} 1 cql_test_1656754113984.cql_test_1656754114051 0.02089071273803711 0.024692535400390625 0.045583248138427734
    INFO  2022-07-02 09:28:34,067 [shard 1] multishard_mutation_query - do_query after read page, cf columns, 4532

last (442) test iteration
    {},{}: {} {} {} 442 cql_test_1656754113984.cql_test_1656754150837 0.06723594665527344 0.05972766876220703 0.12696361541748047
    INFO  2022-07-02 09:29:10,892 [shard 1] multishard_mutation_query - do_query after read page, cf columns, 20705
``` 
Here 4532 and 20705 - the timings of [read_page](https://github.com/scylladb/scylla/blob/master/multishard_mutation_query.cc#L694) for the table `columns`. There is a similar timings growth for other tables.
3. I also added logs to `multishard_combining_reader_v2::fill_buffer`, see a lot of the following:
```
INFO  2022-07-02 09:29:10,877 [shard 1] mutation_reader - multishard_combining_reader_v2::fill_buffer, fragment mem 427, fragment {mutation_fragment: clustering row {position: clustered,ckp{001663716c5f746573745f31363536373534313136303334000176},0} {clustering_row: ck ckp{001663716c5f746573745f31363536373534313136303334000176} dr {deletable_row: {row_tombstone: {tombstone: timestamp=1656754116057551, deletion_time=1656754116}{shadowable tombstone: none}} {{row:
    clustering_order{ atomic_cell{NONE,ts=1656754116033920,expiry=-1,ttl=0} }
    column_name_bytes{ atomic_cell{76,ts=1656754116033920,expiry=-1,ttl=0} }
    kind{ atomic_cell{regular,ts=1656754116033920,expiry=-1,ttl=0} }
    position{ atomic_cell{-1,ts=1656754116033920,expiry=-1,ttl=0} }
    type{ atomic_cell{int,ts=1656754116033920,expiry=-1,ttl=0} }}}}}}
```
So it seems that we get a lot of tombstones from memtable, spend some time processing them, and then [discard](https://github.com/scylladb/scylla/blob/master/db/schema_tables.cc#L967) them just before calculating the digest.

`INFO  2022-07-02 09:29:10,893 [shard 1] schema_diff - map for columns leave 21465, 953, 0, 69, 0`
Here 21465 - timing of [map](https://github.com/scylladb/scylla/blob/master/db/schema_tables.cc#L708) for **columns**, 953 - number of `mut.partition().mutable_clustered_rows().calculate_size()`, 69 - the same after applying `compact_for_schema_digest`.

Is this the expected behavior? Why does processing ~900 mutations takes tens of milliseconds?

**Comment by nyh** [comment]
Right, this is exactly what my profiling showed me (check out the title of the issue, and its first comment). I also stopped short of understanding how such a tiny table, with perhaps a few thousands of tombstones, can take such a long time to calculate the checksum.

If I remember correctly, I verified that this is not a memtable-specific problem: It remains slow after a restart, which rules out the possibility that something is wrong only in the memtable or cache.

**Comment by tgrabiec** [comment]
> Here 4532 and 20705 - the timings of [read_page](https://github.com/scylladb/scylla/blob/master/multishard_mutation_query.cc#L694) for the table columns

What's the unit?

**Comment by tgrabiec** [comment]
Is the result the same as when you don't drop the tables?

**Comment by tgrabiec** [comment]
> Why does processing ~900 mutations takes tens of milliseconds?

You could try profiling with `perf`

**Comment by nyh** [comment]
> Is the result the same as when you don't drop the tables?

Interesting question. The benchmark I ran in https://github.com/scylladb/scylla/issues/7620#issuecomment-1167271218 when iterating over creating-and-deleting a random-named table, when I reran it now, the first iteration took 0.012 seconds, the 1000th iteration took 0.04 - 0.05 seconds. If I don't delete at all, and just create more and more random tables, the first iteration is 0.006 seconds (since it's only a create, not a delete, it takes half the time) but the 1000th iteration - with 1000 live tables - is 0.3 seconds - which is terrible (almost 10 times worse than the create-delete case).

Arguably, the performance when there are really 1000 live tables is less important, because this is not a common case, but I also don't know how to explain the bad performance in that case as well. I suspect the same calculate_schema_digest() bug also happens when there are 1000 live tables, not just 1000 dead tables. The 1000 dead tables case was simply quite common (we saw it both at a real user installation and in several test frameworks), which is why I discovered it first.

**Comment by avikivity** [comment]
Creating a table is O(number of tables), but I don't think it's such an important bug. Creating tables is a very rare operation and users will hardly notice a problem.

If don't create/delete the tables constantly, eventually the tombstones will be garbage collected and asympotically the performance will stabilize. Yes, if your workload is solely create/delete it will be bad, but that's not how the database is normally used.

**Comment by nyh** [comment]
> > It seems that I had some problems with the environment (disks/SSD?) when I ran that test, those problems added the big random delays and masked the initial issue. I'll try to retest.
> 
> On consumer SSDs, --kernel-page-cache and --unsafe-bypass-fsync are recommended (it's still going to be bad).

I checked, and both test.py and test/cql-pytest/run use unsafe-bypass-fsync and kernel-page-cache.

Moreover, test/cql-pytest/run puts the temporary Scylla tables in /tmp (which can be overriden with TMPDIR), which on most developer machines is a ram disk - so the speed of your SSD should be irrelevant when running the test this way.
However, if you use test.py, it indeed defaults to the current directory - not /tmp (you can override it with the --tmpdir option). I consider this a mistake for developer work, but it has historic explanations: Historically, some of the automated testing machines (Jenkins) used a misconfigured disk for /tmp, not tmpfs, and the resulting performance was terrible, so we had to use the current directory instead of /tmp. @avikivity considered it important that `test.py` has the same defaults for both Jenkins and developer use, so we had to make this inefficient default the default for everyone.

By the way, I wouldn't be surprised if part of this bug is doing too much I/O and not (or not just) CPU, which is why you see it much slower on slow disks. But when we have just a thousand deleted tables, the size of the schema sstables is fairly tiny (just a few thousands of tombstones), perhaps a few dozen kilobytes, so even reading the entire schema tables would take a small amount of IO. Unless we're doing this read in some very wrong way.

**Comment by nyh** [comment]
> Creating a table is O(number of tables), but I don't think it's such an important bug. Creating tables is a very rare operation and users will hardly notice a problem.

We had a real user noticing this - see #7594. As I noted above, users will not have a thousand tables concurrently because we don't support this well, but it's not hard to imagine a use case (like this user apparently had...) where tables are being created and deleted often. The total number of tables is small but the number of past tables there were deleted can grow large. I can't say that this is a super-common problem, but I don't think we should just ignore it without understand the cause of this slowdown - maybe it will expose a more serious bug.

As I noted above, I don't know why, but in the past the absolute times were much larger than I see today - maybe because of the bypass-fsync options and tmpfs that we didn't use in the past. The user in #7594 reported very high table-creation times (like 30 seconds) as well as table creation failures.

And this situation is of course super common in tests - where tests would like to create a random-named table, test something on it, and then delete this table. The slowdown caused by this bug had a huge effect on the total runtime of a test suite (see https://github.com/scylladb/scylla/pull/10635) and we had to work around it. Would have been nicer to fix the bug instead of working around it.

> If don't create/delete the tables constantly, eventually the tombstones will be garbage collected and asympotically the performance will stabilize. Yes, if your workload is solely create/delete it will be bad, but that's not how the database is normally used.

Maybe tombstone GC will indeed help, but neither the user who reported this, nor tests, ever waited 10 days to see it help. If may help if a use case has about 100 created/deleted table names a week - if if it's more it won't help (before changing the GC configuration on the schema tables).

**Comment by avikivity** [comment]
Note that the cache does not garbage-collect tombstones.

**Comment by nyh** [comment]
> Note that the cache does not garbage-collect tombstones.

One of first things I verified two years ago when I discovered this issue was that it's probably not related to what's in the cache, because restarting Scylla does not make the slow-table-operations problem go away:
https://github.com/scylladb/scylla/issues/7620#issuecomment-729533178

**Comment by tgrabiec** [comment]
The tombstones are not garbage-collectable anyway, since schema tables use a 7-day gc grace period.

**Comment by gusev-p** [comment]
I drilled into the row_cache, here is [the logs](https://gist.github.com/c4578c0d39ca86c2d1e93c764ed44315) I put into the code, and [this is the log](https://gist.github.com/09e8d9ad8e71291dd3a2dacb2f898a3a) of reading data from the cache during `calculate_schema_digest/query_mutations` for the `columns` table.

In particular, we have a bunch of the following records:
```
INFO  2022-07-12 07:14:34,251 [shard 0] cache - cache_flat_mutation_reader::do_fill_buffer trace18 1199 row_tombstones: 0
INFO  2022-07-12 07:14:34,251 [shard 0] cache - cache_flat_mutation_reader::do_fill_buffer trace20 1650 0 523 0 0 0 true 1 523 523 523 371 894 384420 {mutation_fragment: clustering row {position: clustered,ckp{001663716c5f746573745f31363537363039393533313531000176},0} {clustering_row: ck ckp{001663716c5f746573745f31363537363039393533313531000176} dr {deletable_row: {row_tombstone: {tombstone: timestamp=1657609953173521, deletion_time=1657609953}{shadowable tombstone: none}} {{row:
    clustering_order{ atomic_cell{NONE,ts=1657609953151026,expiry=-1,ttl=0} }
    column_name_bytes{ atomic_cell{76,ts=1657609953151026,expiry=-1,ttl=0} }
    kind{ atomic_cell{regular,ts=1657609953151026,expiry=-1,ttl=0} }
    position{ atomic_cell{-1,ts=1657609953151026,expiry=-1,ttl=0} }
    type{ atomic_cell{int,ts=1657609953151026,expiry=-1,ttl=0} }}}}}}
```
These records wrap [the loop](https://github.com/scylladb/scylla/blob/master/cache_flat_mutation_reader.hh#L407). It means that we read 523 mutations, each of them was a tombstone, and it took 1650 - 1199 == 451 microseconds until we break out of the loop because of `need_preempt()`. There are several calls to `cache_flat_mutation_reader::do_fill_buffer` and they add up to ~4 milliseconds. I'm not sure, but these timings seem normal for this code.

**Comment by gusev-p** [comment]
test run with cache:
```
{},{}: {} {} {} 1 cql_test_1657616682144.cql_test_1657616682205 0.019939661026000977 0.02285313606262207 0.04279279708862305
...
{},{}: {} {} {} 2999 cql_test_1657616682144.cql_test_1657617002542 0.07820749282836914 0.08223152160644531 0.16043901443481445
```

test run without cache (`enable_cache: false` in scylla.yaml, data files are on tmpfs):
```
{},{}: {} {} {} 1 cql_test_1657615987417.cql_test_1657615987468 0.016638517379760742 0.020549774169921875 0.03718829154968262
...
{},{}: {} {} {} 2999 cql_test_1657615987417.cql_test_1657616215442 0.05137372016906738 0.05670785903930664 0.10808157920837402
```
Last number is the time of create/delete table in seconds. So there is a ~3 times slowdown between the first table recreation and the last (2999-th), and the cache makes it slightly worse.

**Comment by tgrabiec** [comment]
> the cache makes it slightly worse.

How much worse?

It's expected that it's a bit worse, because it's not optimized just for reading, but also for updates (RUM conjecture).

**Comment by gusev-p** [comment]
> > the cache makes it slightly worse.
> 
> How much worse?
> 
> It's expected that it's a bit worse, because it's not optimized just for reading, but also for updates (RUM conjecture).

```
without cache: (timing of the last run)0.108 / (timing of the first run) 0.037 == 2.91
with cache: (timing of the last run)0.160 / (timing of the first run) 0.042 == 3.809
```

**Comment by kbr-** [comment]
@tgrabiec shouldn't the situation improve drastically after your memtable flush PR was merged (https://github.com/scylladb/scylla/pull/10333)?

If I understand correctly (please correct me if I'm wrong), before your change each tombstone would live in a separate sstable because every drop table/keyspace mutation would be flushed. So iterating over those tombstones would potentially have to iterate over many sstables, performing a separate read for each.

I'm not taking into account things like cache here so maybe my reasoning is wrong and we didn't really have to do any disk reads?

Anyway, with your change, the tombstones should no longer live separately, so even without any caching reading all of them should require ~1 sstable read (assuming that we don't perform as many schema changes as to flush many sstables).

**Comment by nyh** [comment]
> > > the cache makes it slightly worse.
> > 
> > 
> > How much worse?
> > It's expected that it's a bit worse, because it's not optimized just for reading, but also for updates (RUM conjecture).
> 
> ```
> without cache: (timing of the last run)0.108 / (timing of the first run) 0.037 == 2.91
> with cache: (timing of the last run)0.160 / (timing of the first run) 0.042 == 3.809
> ```

@gusev-p Let's just say that if the time of the last run is 291% slowerthan the first run, that's the more serious problem, not the 30% slowdown (3.809/2.91) caused by the cache.

@kbr- the answer to your question is NO: after you deleted just a few thousand tables and have just a few thousand tombstones (just a few kilobytes on disk!), the time to add another row grows significantly (see numerical examples above). According to my experiments this is not caused by compaction, memtable flush, or caches - the problem remains even if you restart Scylla and everything has already been compacted to one sstable per table (and a fairly tiny sstable, at that - a few thousands tombstones don't take up a lot of space!)

**Comment by nyh** [comment]
> @tgrabiec shouldn't the situation improve drastically after your memtable flush PR was merged (#10333)?
> 
> If I understand correctly (please correct me if I'm wrong), before your change each tombstone would live in a separate sstable because every drop table/keyspace mutation would be flushed. So iterating over those tombstones would potentially have to iterate over many sstables, performing a separate read for each.

According to my experiments, compactions happen all the time and you keep ending up with just one sstable. We can argue this is a waste, but even if it is it doesn't explain why the 3000th iteration is much slower than the first. Compacting two tables with 3000 tombstones shouldn't take so much longer than compacting two tables with 10 tombstones.

**Comment by kostja** [comment]
@gusev-p @tgrabiec I wonder when we switch to timeuuid-based schema id generated in raft, will this issue be gone as well...

**Comment by tgrabiec** [comment]
> @gusev-p @tgrabiec I wonder when we switch to timeuuid-based schema id generated in raft, will this issue be gone as well...

It will be gone, because there will be no calculate_schema_digest().

**Comment by kbr-scylla** [comment]
Ref: https://github.com/scylladb/scylladb/issues/13957

**Comment by nyh** [comment]
> > @gusev-p @tgrabiec I wonder when we switch to timeuuid-based schema id generated in raft, will this issue be gone as well...
> 
> It will be gone, because there will be no calculate_schema_digest().

Obviously, the problem wasn't the name of the function, but the fact that when you create and delete a lot of tables with _different_ names, then:
1. The list of tables stored on disk contained tombstones for deleted tables.
2. Whatever code read this list was very slow (I still don't know why).

You'll need think how the new algorithm doesn't share both - preferably neither - of these traits. You can also try the test I described above - which loops creating a random-named table and deleting it, thousands of times - and see the performance of such a test.

**Comment by tgrabiec** [comment]
> Obviously, the problem wasn't the name of the function

If calculate_schema_digest() is gone, there will be no code which scans everything. Creating a table will read schema tables only for that table.

**Comment by kbr-scylla** [comment]
We read the table definitions using inefficient serial algorithm:
```cpp
static
future<std::map<table_id, schema_mutations>>
read_tables_for_keyspaces(distributed<service::storage_proxy>& proxy, const std::set<sstring>& keyspace_names, schema_ptr s)
{
    std::map<table_id, schema_mutations> result;
    for (auto&& keyspace_name : keyspace_names) {
        for (auto&& table_name : co_await read_table_names_of_keyspace(proxy, keyspace_name, s)) {
            auto qn = qualified_name(keyspace_name, table_name);
            auto muts = co_await read_table_mutations(proxy, qn, s);
            auto id = table_id_from_mutations(muts);
            result.emplace(std::move(id), std::move(muts));
        }
    }
    co_return result;
}
```

**Comment by tgrabiec** [comment]
@kbr-scylla You seen to be working with an old version, without c8e2bf1596be35f1a81004ba145a7e51ec748907

**Comment by kbr-scylla** [comment]
Ah, thanks, I forgot about this patch...

Indeed I was running on `scylla-2023.1.0-rc5`

**Comment by kbr-scylla** [comment]
Damn, indeed, with your fix + schema digest calculations disabled, schema changes are super quick.

**Comment by bhalevy** [comment]
Reopened by https://github.com/scylladb/scylladb/commit/35849fc901cb2d70f6aa18a590c0963ded17d1b7

**Comment by mykaul** [comment]
@kbr-scylla - is this still being worked on for 5.4?

**Comment by kbr-scylla** [comment]
Realistically, it won't go into 5.4.

**Comment by denesb** [comment]
@kbr- does this have to be backported?

**Comment by kbr-scylla** [comment]
Definitely not, group 0 schema versioning is a relatively major feature

**Comment by mykaul** [comment]
milestone here is Yellofin - I assume it should be 6.0 or something?
