### ISSUE TITLE
LWT operation latency will be affected by 'Requesting schema pull'?

### ISSUE THREAD

**Issue by Felix-zhoux** [scylladb/scylladb#9275]
scylla version 4.4.1

The latency of the `PutItem` request using LWT becomes very high (where latency of other requests are normal ) after recovering from the fault. 

A node in the cluster was down for about **30 hours** due to a system failure. After restarting the scylla service, it was found that the **latency of PutItem request using LWT** of this node was very high, reaching 300-500ms (about 6ms before the failure). Check the node's log and found that after the failure recovery, this node has been performing the following operations, which lasted more than 1 day, and are still executing:

```
# journalctl _COMM=scylla |grep migration_manager
Aug 30 17:34:02 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Requesting schema pull from 10.214.185.131:28
Aug 30 17:34:02 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Pulling schema from 10.214.185.131:28
Aug 30 17:34:04 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Requesting schema pull from 10.214.185.130:35
Aug 30 17:34:04 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Pulling schema from 10.214.185.130:35
Aug 30 17:34:04 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Schema merge with 10.214.185.131:28 completed
Aug 30 17:34:06 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Schema merge with 10.214.185.130:35 completed
Aug 30 17:34:09 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Requesting schema pull from 10.214.185.129:32
Aug 30 17:34:09 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Pulling schema from 10.214.185.129:32
Aug 30 17:34:12 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Requesting schema pull from 10.227.16.129:11
Aug 30 17:34:12 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Pulling schema from 10.227.16.129:11
Aug 30 17:34:13 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Schema merge with 10.214.185.129:32 completed
Aug 30 17:34:15 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Requesting schema pull from 10.214.185.131:35
Aug 30 17:34:15 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Pulling schema from 10.214.185.131:28
Aug 30 17:34:20 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Schema merge with 10.227.16.129:11 completed
Aug 30 17:34:25 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Schema merge with 10.214.185.131:28 completed
Aug 30 17:34:27 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Requesting schema pull from 10.214.185.131:1
Aug 30 17:34:27 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Pulling schema from 10.214.185.131:28
Aug 30 17:34:28 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Requesting schema pull from 10.214.185.130:38
Aug 30 17:34:28 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Pulling schema from 10.214.185.130:35
Aug 30 17:34:31 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Schema merge with 10.214.185.131:28 completed
Aug 30 17:34:34 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Schema merge with 10.214.185.130:35 completed
Aug 30 17:34:41 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Requesting schema pull from 10.223.117.131:49
Aug 30 17:34:41 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Pulling schema from 10.223.117.131:49
Aug 30 17:34:43 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Schema merge with 10.223.117.131:49 completed
Aug 30 17:38:37 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Requesting schema pull from 10.214.185.131:12
Aug 30 17:38:37 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Pulling schema from 10.214.185.131:28
Aug 30 17:38:37 HOSTNAME-02 scylla[19864]:  [shard 0] migration_manager - Schema merge with 10.214.185.131:28 completed
...
```

So my question is whether ‘Requesting schema pull’ will affect the latency of LWT operations?
Why is ‘Requesting schema pull’ executed and how long will it last?

From the traing log , I can see that latency of 'Sending a learn' or before is normal , and  'Committing decision proposal' was delayed.

**Comment by nyh** [comment]
@Felix-zhoux can you try to increase the `migration_manager` log level, perhaps we'll get additional logging messages.

It is reasonable that after a node has been down for 30 hours, it is missing the latest version of the schema so needs to pull it. However, what appears bad here is that it seems to be doing this in a loop, without converging. @asias do you have any idea why this might be happening? Note that this user is using a somewhat old version (4.4.1) - has anything been fixed in this area recently?

@gleb-cloudius @kostja the user suspects that this schema pull is slowing down one particular phase of the LWT write that waits for it - is this expected? Could there be a reason why this pull might be wrong in some way (wrong version?) and need to happen again and again?

**Comment by gleb-cloudius** [comment]
Shema pull we affect the latency of any operation since it wait for schema synchronization before completing an operation , but it should have happened only once.

**Comment by nyh** [comment]
I asked around, and it turns out that in some rare cases (which we still haven't managed to completely fix), the schema on different nodes can get out of sync and fail to synchronize. We have an FAQ entry about this - https://docs.scylladb.com/troubleshooting/error_messages/schema_mismatch/
That link explains how to verify that you have this problem, and if you do, how to solve it with a "rolling restart" (draining and restarting nodes one by one).

Another not-very-pretty solution given that you have just one node with the problem is to remove this node and replace it with a new one.

Of course it would be great to try to debug **why** this schema problem happened in the first place, but I don't know how to reproduce the problem.

**Comment by Felix-zhoux** [comment]
> @Felix-zhoux can you try to increase the migration_manager log level, perhaps we'll get additional logging messages.

@nyh  I set migration_manager log level to trace and collected logs of 3 nodes for about 5 minutes.
After the HOSTNAME-01 node (not the failed node) restarted the service, an abnormal LWT delay also occurred.
The HOSTNAME-02 node (faulty node) delay problem still exists
The HOSTNAME-03 node (not the failed node), did not restart the service, the delay was normal.

Here is the log:
[endless loop of schema pulling.txt](https://github.com/scylladb/scylla/files/7104144/endless.loop.of.schema.pulling.txt)

Actual with command `nodetool describecluster`, I see that **Schema versions was always the same** (and **with no change** '4ab58b56-cfa0-3805-99c1-64d0e36bc6cd' ) among nodes. 
This makes me feel puzzled, it seems that this problem is not necessarily related to the failure of HOSTNAME-02 node for 30h?

**Comment by Felix-zhoux** [comment]
> @Felix-zhoux can you try to increase the migration_manager log level, perhaps we'll get additional logging messages.

@nyh  I set migration_manager log level to trace and collected logs of 3 nodes for about 5 minutes.
After the HOSTNAME-01 node (not the failed node) restarted the service, an abnormal LWT delay also occurred.
The HOSTNAME-02 node (faulty node) delay problem still exists
The HOSTNAME-03 node (not the failed node), did not restart the service, the delay was normal.

Here is the log:
[endless loop of schema pulling.txt](https://github.com/scylladb/scylla/files/7104144/endless.loop.of.schema.pulling.txt)

Actual with command `nodetool describecluster`, I see that **Schema versions was always the same** (and **with no change** '4ab58b56-cfa0-3805-99c1-64d0e36bc6cd' ) among nodes. 
This makes me feel puzzled, it seems that this problem is not necessarily related to the failure of HOSTNAME-02 node for 30h?

**Comment by nyh** [comment]
I'm not an expert in the schema-changes code (I hope @gleb-cloudius is a bit more than me), but I want to try to summarize what I see:

At some point, the schema of your table changed to `4ab58b56-cfa0-3805-99c1-64d0e36bc6cd`. This is what you see in `nodetool describecluster`, and in your log of the rebooted (but otherwise fine!) node we see in the beginning that it also picked up this version after the reboot:
```
Sep 03 09:11:09 HOSTNAME-01 scylla[35507]:  [shard 0] schema_tables - Schema version changed to 4ab58b56-cfa0-3805-99c1-64d0e36bc6cd
```
And yet, we see in the same node, for a couple of minutes afterwords,
```
Sep 03 09:13:04 HOSTNAME-01 scylla[35507]:  [shard 6] migration_manager - Schema version request for e4890b19-1f22-3169-964f-e7b80e809932
```
So something - perhaps in the LWT code - remembers an older schema version that nobody remembers by now?
@gleb-cloudius is it perhaps possible that in some internal LWT table  we hold a record with an older schema, and if we can't find this record we go into some endless loop where we can't clear this record and keep asking for the no-longer-existing schema version?

In the same log, I also see the following another two minutes later:
```
Sep 03 09:15:12 HOSTNAME-01 scylla[35507]:  [shard 0] migration_manager - Requesting schema pull from 10.223.117.131:94
Sep 03 09:15:12 HOSTNAME-01 scylla[35507]:  [shard 0] migration_manager - Pulling schema from 10.223.117.131:0
Sep 03 09:15:13 HOSTNAME-01 scylla[35507]:  [shard 0] schema_tables - Schema version changed to 4ab58b56-cfa0-3805-99c1-64d0e36bc6cd
Sep 03 09:15:13 HOSTNAME-01 scylla[35507]:  [shard 0] migration_manager - Schema merge with 10.223.117.131:0 completed
```
I don't know *why* we requested this schema pull, but after it we are left with exactly the same version.

**Comment by kostja** [comment]
Should be addressed by consistent schema changes, closing.
